from .orm_models import (
    OldAdaptableExercise as OldAdaptableExercise,
    OldAdaptation as OldAdaptation,
    OldAdaptationBatch as OldAdaptationBatch,
    OldAdaptationStrategy as OldAdaptationStrategy,
    OldAdaptationStrategySettings as OldAdaptationStrategySettings,
    OldBaseExercise as OldBaseExercise,
    OldClassificationBatch as OldClassificationBatch,
    OldExerciseClass as OldExerciseClass,
    OldExternalExercise as OldExternalExercise,
    OldExtractionBatch as OldExtractionBatch,
    OldExtractionStrategy as OldExtractionStrategy,
    OldPageExtraction as OldPageExtraction,
    OldPdfFile as OldPdfFile,
    OldPdfFileRange as OldPdfFileRange,
    OldTextbook as OldTextbook,
)
