from typing import Sequence, Union

from alembic import op

revision: str = "0311b64d31be"
down_revision: Union[str, None] = "b9223189b6ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("old_external_exercises")
    op.drop_table("old_adaptable_exercises")
    op.drop_table("old_adaptation_strategies")
    op.drop_table("old_exercise_classes")
    op.drop_table("old_extraction_batches")
    op.drop_table("old_page_extractions")
    op.drop_table("old_textbooks")
    op.drop_table("old_pdf_file_ranges")
    op.drop_table("old_pdf_files")
    op.drop_table("old_adaptations")
    op.drop_table("old_exercises")
    op.drop_table("old_extraction_strategies")
    op.drop_table("old_adaptation_strategy_settings")
    op.drop_table("old_adaptation_batches")
    op.drop_table("old_classification_batches")
    # ### end Alembic commands ###
