from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "136b39dc2bcf"
down_revision: Union[str, None] = "ac3c4bcfd7f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("adaptations", sa.Column("initial_timing", sa.JSON(), nullable=True))
    op.add_column("classification_chunks", sa.Column("timing", sa.JSON(), nullable=True))
    op.add_column("page_extractions", sa.Column("timing", sa.JSON(), nullable=True))
    # ### end Alembic commands ###
