from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "159443568b4e"
down_revision: Union[str, None] = "239538041ab7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("adaptation_strategies", "settings_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_column("adaptation_strategies", "system_prompt")
    op.drop_column("adaptation_strategies", "response_specification")
    # ### end Alembic commands ###
