from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "21097ee8a980"
down_revision: Union[str, None] = "63b6144a6460"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "extraction_settings", sa.Column("output_schema_version", sa.String(), server_default="v2", nullable=False)
    )
    # ### end Alembic commands ###
