from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "239538041ab7"
down_revision: Union[str, None] = "46a2d41cd509"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "adaptation_strategy_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("system_prompt", sa.String(), nullable=False),
        sa.Column("response_specification", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_adaptation_strategy_settings")),
    )
    op.add_column("adaptation_strategies", sa.Column("settings_id", sa.Integer(), nullable=True))
    op.alter_column("adaptation_strategies", "system_prompt", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "adaptation_strategies",
        "response_specification",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
    )
    op.create_foreign_key(
        op.f("fk_adaptation_strategies_settings_id_adaptation_strategy_settings"),
        "adaptation_strategies",
        "adaptation_strategy_settings",
        ["settings_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_adaptation_strategies_settings_id_adaptation_strategy_settings"),
        "adaptation_strategies",
        type_="foreignkey",
    )
    op.alter_column(
        "adaptation_strategies",
        "response_specification",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column("adaptation_strategies", "system_prompt", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("adaptation_strategies", "settings_id")
    op.drop_table("adaptation_strategy_settings")
    # ### end Alembic commands ###
