from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "2d779fc6a028"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "adaptation_input",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_adaptation_input")),
    )
    op.create_table(
        "adaptation_strategies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("model", sa.JSON(), nullable=False),
        sa.Column("system_prompt", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["adaptation_strategies.id"],
            name=op.f("fk_adaptation_strategies_parent_id_adaptation_strategies"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_adaptation_strategies")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("adaptation_strategies")
    op.drop_table("adaptation_input")
    # ### end Alembic commands ###
