from typing import Sequence, Union

from alembic import op

revision: str = "2f373916373a"
down_revision: Union[str, None] = "d710f60075da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("extraction_batches", "sandbox_extraction_batches")
    op.drop_constraint(
        op.f("fk_page_extraction_creations__by_sandbox_extraction_bat_df20"),
        "page_extraction_creations__by_sandbox_extraction_batch",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f(
            "fk_page_extraction_creations__by_sandbox_extraction_batch_sandbox_extraction_batch_id_sandbox_extraction_batches"
        ),
        "page_extraction_creations__by_sandbox_extraction_batch",
        "sandbox_extraction_batches",
        ["sandbox_extraction_batch_id"],
        ["id"],
    )
    # ### end Alembic commands ###
