# Copyright 2025 Vincent Jacques <vincent@vincent-jacques.net>

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "45f38dacee6f"
down_revision: Union[str, None] = "6eed4e92a1a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lessons",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("textbook_id", sa.Integer(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("original_file_name", sa.String(), nullable=False),
        sa.Column("removed_from_textbook", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["textbook_id"], ["textbooks.id"], name=op.f("fk_lessons_textbook_id_textbooks")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lessons")),
    )
    op.create_table(
        "adaptation_creations__by_textbook",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("textbook_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["adaptation_creations.id"],
            name=op.f("fk_adaptation_creations__by_textbook_id_adaptation_creations"),
        ),
        sa.ForeignKeyConstraint(
            ["textbook_id"], ["textbooks.id"], name=op.f("fk_adaptation_creations__by_textbook_textbook_id_textbooks")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_adaptation_creations__by_textbook")),
    )
    # ### end Alembic commands ###
