# MALIN Platform https://malin.cahiersfantastiques.fr/
# Copyright 2025 Vincent Jacques <vincent@vincent-jacques.net>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "45f38dacee6f"
down_revision: Union[str, None] = "6eed4e92a1a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lessons",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("textbook_id", sa.Integer(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("original_file_name", sa.String(), nullable=False),
        sa.Column("removed_from_textbook", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["textbook_id"], ["textbooks.id"], name=op.f("fk_lessons_textbook_id_textbooks")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lessons")),
    )
    op.create_table(
        "adaptation_creations__by_textbook",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("textbook_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["adaptation_creations.id"],
            name=op.f("fk_adaptation_creations__by_textbook_id_adaptation_creations"),
        ),
        sa.ForeignKeyConstraint(
            ["textbook_id"], ["textbooks.id"], name=op.f("fk_adaptation_creations__by_textbook_textbook_id_textbooks")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_adaptation_creations__by_textbook")),
    )
    # ### end Alembic commands ###
