from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "46a2d41cd509"
down_revision: Union[str, None] = "429d2fb463dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("adaptation_input", sa.Column("page_number", sa.Integer(), nullable=True))
    op.add_column(
        "adaptation_input", sa.Column("exercise_number", sa.String(collation="exercise_number"), nullable=True)
    )
    # ### end Alembic commands ###
    op.create_check_constraint("exercise_number_not_empty", "adaptation_input", "exercise_number != ''")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("adaptation_input", "exercise_number")
    op.drop_column("adaptation_input", "page_number")
    # ### end Alembic commands ###
