# MALIN Platform https://malin.cahiersfantastiques.fr/
# Copyright 2025 Vincent Jacques <vincent@vincent-jacques.net>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "496af6d75cf6"
down_revision: Union[str, None] = "429d2fb463dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "errors_caught_by_frontend",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_username", sa.String(), nullable=True),
        sa.Column("patty_version", sa.String(), nullable=False),
        sa.Column("user_agent", sa.String(), nullable=False),
        sa.Column("window_size", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("caught_by", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("code_location", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_errors_caught_by_frontend")),
    )
    # ### end Alembic commands ###
