from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "496af6d75cf6"
down_revision: Union[str, None] = "d7666007b1be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "errors_caught_by_frontend",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_username", sa.String(), nullable=True),
        sa.Column("patty_version", sa.String(), nullable=False),
        sa.Column("user_agent", sa.String(), nullable=False),
        sa.Column("window_size", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("caught_by", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("code_location", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_errors_caught_by_frontend")),
    )
    # ### end Alembic commands ###
