# MALIN Platform https://malin.cahiersfantastiques.fr/
# Copyright 2025 Vincent Jacques <vincent@vincent-jacques.net>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "60fe45b075e7"
down_revision: Union[str, None] = "0311b64d31be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("errors_caught_by_frontend", sa.Column("github_issue_number", sa.Integer(), nullable=True))
    op.add_column(
        "page_extraction_creations__by_textbook",
        sa.Column("removed_from_textbook", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###
