from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "60fe45b075e7"
down_revision: Union[str, None] = "0311b64d31be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("errors_caught_by_frontend", sa.Column("github_issue_number", sa.Integer(), nullable=True))
    op.add_column(
        "page_extraction_creations__by_textbook",
        sa.Column("removed_from_textbook", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###
