from typing import Sequence, Union
import textwrap

from alembic import op
import sqlalchemy as sql


revision: str = "63b6144a6460"
down_revision: Union[str, None] = "b48e74b86562"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Remove now-unused collation 'exercise_number'
    op.execute(
        sql.text(
            textwrap.dedent(
                """\
                ALTER TABLE exercise_locations__maybe_page_and_number
                ALTER COLUMN exercise_number
                TYPE varchar COLLATE "default" USING exercise_number::varchar
                """
            )
        )
    )
    op.execute(
        sql.text(
            textwrap.dedent(
                """\
                ALTER TABLE exercise_locations__textbook
                ALTER COLUMN exercise_number
                TYPE varchar COLLATE "default" USING exercise_number::varchar
                """
            )
        )
    )
    op.execute(sql.text("DROP COLLATION exercise_number"))

    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
