# MALIN Platform https://malin.cahiersfantastiques.fr/
# Copyright 2025 Vincent Jacques <vincent@vincent-jacques.net>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

from typing import Sequence, Union
import textwrap

from alembic import op
import sqlalchemy as sql


revision: str = "63b6144a6460"
down_revision: Union[str, None] = "b48e74b86562"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Remove now-unused collation 'exercise_number'
    op.execute(
        sql.text(
            textwrap.dedent(
                """\
                ALTER TABLE exercise_locations__maybe_page_and_number
                ALTER COLUMN exercise_number
                TYPE varchar COLLATE "default" USING exercise_number::varchar
                """
            )
        )
    )
    op.execute(
        sql.text(
            textwrap.dedent(
                """\
                ALTER TABLE exercise_locations__textbook
                ALTER COLUMN exercise_number
                TYPE varchar COLLATE "default" USING exercise_number::varchar
                """
            )
        )
    )
    op.execute(sql.text("DROP COLLATION exercise_number"))

    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
