# Copyright 2025 Vincent Jacques <vincent@vincent-jacques.net>

from typing import Sequence, Union

from alembic import op


revision: str = "6eed4e92a1a5"
down_revision: Union[str, None] = "21097ee8a980"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("adaptation_creations__by_user")
    # ### end Alembic commands ###
