from typing import Sequence, Union

from alembic import op

revision: str = "8428857d1254"
down_revision: Union[str, None] = "925936b35d15"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("adaptation_batches", "sandbox_adaptation_batches")
    op.drop_constraint(op.f("fk_adaptations_adaptation_batch_id_adaptation_batches"), "adaptations", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_adaptations_adaptation_batch_id_sandbox_adaptation_batches"),
        "adaptations",
        "sandbox_adaptation_batches",
        ["adaptation_batch_id"],
        ["id"],
    )
    # ### end Alembic commands ###
