from typing import Sequence, Union

from alembic import op

revision: str = "925936b35d15"
down_revision: Union[str, None] = "d23d851c70a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("classification_batches", "sandbox_classification_batches")
    op.drop_constraint(
        op.f("fk_adaptable_exercises_classified_by_classification_bat_228b"), "adaptable_exercises", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_adaptable_exercises_classified_by_classification_batch_id_sandbox_classification_batches"),
        "adaptable_exercises",
        "sandbox_classification_batches",
        ["classified_by_classification_batch_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_adaptation_strategies_created_by_classification_batc_a26b"),
        "adaptation_strategies",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_adaptation_strategies_created_by_classification_batch_id_sandbox_classification_batches"),
        "adaptation_strategies",
        "sandbox_classification_batches",
        ["created_by_classification_batch_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_adaptations_classification_batch_id_classification_batches"), "adaptations", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_adaptations_classification_batch_id_sandbox_classification_batches"),
        "adaptations",
        "sandbox_classification_batches",
        ["classification_batch_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_exercise_classes_created_by_classification_batch_id__2337"), "exercise_classes", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_exercise_classes_created_by_classification_batch_id_sandbox_classification_batches"),
        "exercise_classes",
        "sandbox_classification_batches",
        ["created_by_classification_batch_id"],
        ["id"],
    )
    op.execute("ALTER SEQUENCE classification_batches_id_seq RENAME TO sandbox_classification_batches_id_seq")
    # ### end Alembic commands ###
