# Copyright 2025 Vincent Jacques <vincent@vincent-jacques.net>

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "ac3c4bcfd7f2"
down_revision: Union[str, None] = "dcf53c224c71"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("textbooks", sa.Column("pages_count", sa.Integer(), nullable=True))
    # ### end Alembic commands ###
