from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "b48e74b86562"
down_revision: Union[str, None] = "136b39dc2bcf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("textbooks", sa.Column("single_pdf_file_sha256", sa.String(), nullable=True))
    op.create_foreign_key(
        op.f("fk_textbooks_single_pdf_file_sha256_pdf_files"),
        "textbooks",
        "pdf_files",
        ["single_pdf_file_sha256"],
        ["sha256"],
    )
    # ### end Alembic commands ###
