from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "c58370feed85"
down_revision: Union[str, None] = "159443568b4e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "adaptation_external_exercises",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("textbook_id", sa.Integer(), nullable=False),
        sa.Column("removed_from_textbook", sa.Boolean(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("exercise_number", sa.String(collation="exercise_number"), nullable=True),
        sa.Column("original_file_name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["textbook_id"],
            ["adaptation_textbooks.id"],
            name=op.f("fk_adaptation_external_exercises_textbook_id_adaptation_textbooks"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_adaptation_external_exercises")),
    )
    # ### end Alembic commands ###
