from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "d23d851c70a4"
down_revision: Union[str, None] = "2f373916373a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "textbook_starting_points",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("textbook_id", sa.Integer(), nullable=True),
        sa.Column("textbook_first_page_number", sa.Integer(), nullable=True),
        sa.Column("created_by_username", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["textbook_id"], ["textbooks.id"], name=op.f("fk_textbook_starting_points_textbook_id_textbooks")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_textbook_starting_points")),
    )
    op.create_table(
        "pdf_file_textbook_mappings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("pdf_file_range_id", sa.Integer(), nullable=False),
        sa.Column("textbook_starting_point_id", sa.Integer(), nullable=True),
        sa.Column("created_by_username", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["pdf_file_range_id"],
            ["pdf_file_ranges.id"],
            name=op.f("fk_pdf_file_textbook_mappings_pdf_file_range_id_pdf_file_ranges"),
        ),
        sa.ForeignKeyConstraint(
            ["textbook_starting_point_id"],
            ["textbook_starting_points.id"],
            name=op.f("fk_pdf_file_textbook_mappings_textbook_starting_point_id_textbook_starting_points"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pdf_file_textbook_mappings")),
    )
    op.create_table(
        "page_extraction_creations__by_pdf_file_textbook_mapping",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pdf_file_textbook_mapping_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["page_extraction_creations.id"],
            name=op.f("fk_page_extraction_creations__by_pdf_file_textbook_mapping_id_page_extraction_creations"),
        ),
        sa.ForeignKeyConstraint(
            ["pdf_file_textbook_mapping_id"],
            ["pdf_file_textbook_mappings.id"],
            name=op.f(
                "fk_page_extraction_creations__by_pdf_file_textbook_mapping_pdf_file_textbook_mapping_id_pdf_file_textbook_mappings"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_page_extraction_creations__by_pdf_file_textbook_mapping")),
    )
    # ### end Alembic commands ###
