from typing import Sequence, Union

from alembic import op


revision: str = "d710f60075da"
down_revision: Union[str, None] = "496af6d75cf6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column("textbooks", "editor", new_column_name="publisher")
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
