from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "d710f60075da"
down_revision: Union[str, None] = "496af6d75cf6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column("textbooks", "editor", new_column_name="publisher")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exercise_creations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exercise_creations")),
    )
    op.create_table(
        "exercise_creations__by_user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"], ["exercise_creations.id"], name=op.f("fk_exercise_creations__by_user_id_exercise_creations")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exercise_creations__by_user")),
    )
    op.create_table(
        "exercise_creations__by_page_extraction",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("page_extraction_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["exercise_creations.id"],
            name=op.f("fk_exercise_creations__by_page_extraction_id_exercise_creations"),
        ),
        sa.ForeignKeyConstraint(
            ["page_extraction_id"],
            ["page_extractions.id"],
            name=op.f("fk_exercise_creations__by_page_extraction_page_extraction_id_page_extractions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exercise_creations__by_page_extraction")),
    )
    op.add_column("exercises", sa.Column("created_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_exercises_created_id_exercise_creations"), "exercises", "exercise_creations", ["created_id"], ["id"]
    )
    # ### end Alembic commands ###
