from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "d7666007b1be"
down_revision: Union[str, None] = "f508779ee3fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("textbooks", sa.Column("editor", sa.String(), nullable=True))
    op.add_column("textbooks", sa.Column("year", sa.Integer(), nullable=True))
    op.add_column("textbooks", sa.Column("isbn", sa.String(), nullable=True))
    # ### end Alembic commands ###
