from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "dcf53c224c71"
down_revision: Union[str, None] = "60fe45b075e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exercise_images",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("local_identifier", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exercise_images")),
    )
    op.create_table(
        "exercise_image_creations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"], ["exercise_images.id"], name=op.f("fk_exercise_image_creations_id_exercise_images")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exercise_image_creations")),
    )
    op.create_table(
        "exercise_image_creations__by_page_extraction",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("page_extraction_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["exercise_image_creations.id"],
            name=op.f("fk_exercise_image_creations__by_page_extraction_id_exercise_image_creations"),
        ),
        sa.ForeignKeyConstraint(
            ["page_extraction_id"],
            ["page_extractions.id"],
            name=op.f("fk_exercise_image_creations__by_page_extraction_page_extraction_id_page_extractions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exercise_image_creations__by_page_extraction")),
    )
    # ### end Alembic commands ###
