/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/adaptable-exercises/{id}/exercise-class': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Put Adaptable Exercise Class */
    put: operations['put_adaptable_exercise_class_api_adaptable_exercises__id__exercise_class_put']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/adaptation-batches': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Adaptation Batches */
    get: operations['get_adaptation_batches_api_adaptation_batches_get']
    put?: never
    /** Post Adaptation Batch */
    post: operations['post_adaptation_batch_api_adaptation_batches_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/adaptation-batches/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Adaptation Batch */
    get: operations['get_adaptation_batch_api_adaptation_batches__id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/adaptation-llm-response-schema': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Make Adaptation Llm Response Schema */
    post: operations['make_adaptation_llm_response_schema_api_adaptation_llm_response_schema_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/adaptations/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Adaptation */
    get: operations['get_adaptation_api_adaptations__id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/adaptations/{id}/adjustment': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Post Adaptation Adjustment */
    post: operations['post_adaptation_adjustment_api_adaptations__id__adjustment_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/adaptations/{id}/last-adjustment': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Delete Adaptation Last Adjustment */
    delete: operations['delete_adaptation_last_adjustment_api_adaptations__id__last_adjustment_delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/adaptations/{id}/manual-edit': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Put Adaptation Manual Edit */
    put: operations['put_adaptation_manual_edit_api_adaptations__id__manual_edit_put']
    post?: never
    /** Delete Adaptation Manual Edit */
    delete: operations['delete_adaptation_manual_edit_api_adaptations__id__manual_edit_delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/available-adaptation-llm-models': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Available Adaptation Llm Models */
    get: operations['get_available_adaptation_llm_models_api_available_adaptation_llm_models_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/available-extraction-llm-models': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Available Extraction Llm Models */
    get: operations['get_available_extraction_llm_models_api_available_extraction_llm_models_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/base-adaptation-batch': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Base Adaptation Batch */
    get: operations['get_base_adaptation_batch_api_base_adaptation_batch_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/classification-batches': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Classification Batches */
    get: operations['get_classification_batches_api_classification_batches_get']
    put?: never
    /** Create Classification Batch */
    post: operations['create_classification_batch_api_classification_batches_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/classification-batches/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Classification Batch */
    get: operations['get_classification_batch_api_classification_batches__id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/classification-batches/{id}/model-for-adaptation': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Put Classification Batch Model For Adaptation */
    put: operations['put_classification_batch_model_for_adaptation_api_classification_batches__id__model_for_adaptation_put']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/classification-batches/{id}/submit-adaptations-with-recent-settings': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Submit Adaptations With Recent Settings In Classification Batch */
    post: operations['submit_adaptations_with_recent_settings_in_classification_batch_api_classification_batches__id__submit_adaptations_with_recent_settings_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/errors-caught-by-frontend': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Retrieve Errors */
    get: operations['retrieve_errors_api_errors_caught_by_frontend_get']
    put?: never
    /** Create Error */
    post: operations['create_error_api_errors_caught_by_frontend_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/exercise-classes': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Exercise Classes */
    get: operations['get_exercise_classes_api_exercise_classes_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/extraction-batches': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Extraction Batches */
    get: operations['get_extraction_batches_api_extraction_batches_get']
    put?: never
    /** Create Extraction Batch */
    post: operations['create_extraction_batch_api_extraction_batches_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/extraction-batches/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Extraction Batch */
    get: operations['get_extraction_batch_api_extraction_batches__id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/extraction-batches/{id}/model-for-adaptation': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Put Extraction Batch Model For Adaptation */
    put: operations['put_extraction_batch_model_for_adaptation_api_extraction_batches__id__model_for_adaptation_put']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/extraction-batches/{id}/run-classification': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Put Extraction Batch Run Classification */
    put: operations['put_extraction_batch_run_classification_api_extraction_batches__id__run_classification_put']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/extraction-batches/{id}/submit-adaptations-with-recent-settings': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Submit Adaptations With Recent Settings In Extraction Batch */
    post: operations['submit_adaptations_with_recent_settings_in_extraction_batch_api_extraction_batches__id__submit_adaptations_with_recent_settings_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/extraction-llm-response-schema': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Extraction Llm Response Schema */
    get: operations['get_extraction_llm_response_schema_api_extraction_llm_response_schema_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/latest-extraction-strategy': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Latest Extraction Strategy */
    get: operations['get_latest_extraction_strategy_api_latest_extraction_strategy_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/pdf-files': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Create Pdf File */
    post: operations['create_pdf_file_api_pdf_files_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/textbooks': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Textbooks */
    get: operations['get_textbooks_api_textbooks_get']
    put?: never
    /** Post Textbook */
    post: operations['post_textbook_api_textbooks_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/textbooks/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Textbook */
    get: operations['get_textbook_api_textbooks__id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/textbooks/{id}/ranges': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Post Textbook Range */
    post: operations['post_textbook_range_api_textbooks__id__ranges_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/textbooks/{textbook_id}/exercises/{exercise_id}/removed': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Put Textbook Exercises Removed */
    put: operations['put_textbook_exercises_removed_api_textbooks__textbook_id__exercises__exercise_id__removed_put']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/textbooks/{textbook_id}/external-exercises': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Post Textbook External Exercises */
    post: operations['post_textbook_external_exercises_api_textbooks__textbook_id__external_exercises_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/textbooks/{textbook_id}/ranges/{range_id}/removed': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Put Textbook Ranges Removed */
    put: operations['put_textbook_ranges_removed_api_textbooks__textbook_id__ranges__range_id__removed_put']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/token': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Login */
    post: operations['login_api_token_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    'ActiveFormatted-Input': {
      /**
       * Bold
       * @default false
       */
      bold?: boolean
      /**
       * Boxed
       * @default false
       */
      boxed?: boolean
      /** Contents */
      contents: (
        | components['schemas']['Text']
        | components['schemas']['Whitespace']
        | components['schemas']['Arrow']
        | components['schemas']['ActiveFormatted-Input']
        | components['schemas']['FreeTextInput']
      )[]
      /** Highlighted */
      highlighted?: string | null
      /**
       * Italic
       * @default false
       */
      italic?: boolean
      /**
       * Kind
       * @constant
       */
      kind: 'formatted'
      /**
       * Subscript
       * @default false
       */
      subscript?: boolean
      /**
       * Superscript
       * @default false
       */
      superscript?: boolean
      /**
       * Underlined
       * @default false
       */
      underlined?: boolean
    }
    'ActiveFormatted-Output': {
      /**
       * Bold
       * @default false
       */
      bold?: boolean
      /**
       * Boxed
       * @default false
       */
      boxed?: boolean
      /** Contents */
      contents: (
        | components['schemas']['Text']
        | components['schemas']['Whitespace']
        | components['schemas']['Arrow']
        | components['schemas']['ActiveFormatted-Output']
        | components['schemas']['FreeTextInput']
      )[]
      /** Highlighted */
      highlighted?: string | null
      /**
       * Italic
       * @default false
       */
      italic?: boolean
      /**
       * Kind
       * @constant
       */
      kind: 'formatted'
      /**
       * Subscript
       * @default false
       */
      subscript?: boolean
      /**
       * Superscript
       * @default false
       */
      superscript?: boolean
      /**
       * Underlined
       * @default false
       */
      underlined?: boolean
    }
    /** AdaptationBatch */
    AdaptationBatch: {
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string
      /** Createdby */
      createdBy: string
      /** Id */
      id: string
      /** Model */
      model:
        | components['schemas']['DummyModel']
        | components['schemas']['MistralAiModel']
        | components['schemas']['OpenAiModel']
      strategySettingsIdentity: components['schemas']['Identity'] | null
    }
    /** Adjustment */
    Adjustment: {
      /** Assistantresponse */
      assistantResponse:
        | components['schemas']['patty__adaptation__assistant_responses__Success']
        | components['schemas']['InvalidJsonError']
        | components['schemas']['NotJsonError']
        | components['schemas']['UnknownError']
      /** Userprompt */
      userPrompt: string
    }
    /** ApiAdaptation */
    ApiAdaptation: {
      /** Adaptationbatchid */
      adaptationBatchId: string | null
      /** Adjustments */
      adjustments: components['schemas']['Adjustment'][]
      /** Classificationbatchid */
      classificationBatchId: string | null
      /** Extractionbatchid */
      extractionBatchId: string | null
      /** Id */
      id: string
      /** Initialassistantresponse */
      initialAssistantResponse:
        | components['schemas']['patty__adaptation__assistant_responses__Success']
        | components['schemas']['InvalidJsonError']
        | components['schemas']['NotJsonError']
        | components['schemas']['UnknownError']
        | null
      input: components['schemas']['ApiInput']
      manualEdit: components['schemas']['RootModel_Union_ExerciseV1__ExerciseV2__-Output'] | null
      /** Rawllmconversations */
      rawLlmConversations: unknown[]
      /** Removedfromtextbook */
      removedFromTextbook: boolean
      strategy: components['schemas']['ApiStrategy-Output']
      /** Textbookid */
      textbookId: string | null
      /** Textbooktitle */
      textbookTitle: string | null
    }
    /** ApiExtractionStrategy */
    ApiExtractionStrategy: {
      /** Id */
      id: string
      /** Model */
      model: components['schemas']['DummyModel'] | components['schemas']['GeminiModel']
      /** Prompt */
      prompt: string
    }
    /** ApiInput */
    ApiInput: {
      /** Exercisenumber */
      exerciseNumber: string | null
      /** Pagenumber */
      pageNumber: number | null
      /** Text */
      text: string
    }
    /** ApiStrategy */
    'ApiStrategy-Input': {
      /** Model */
      model:
        | components['schemas']['DummyModel']
        | components['schemas']['MistralAiModel']
        | components['schemas']['OpenAiModel']
      settings: components['schemas']['ApiStrategySettings-Input']
    }
    /** ApiStrategy */
    'ApiStrategy-Output': {
      /** Model */
      model:
        | components['schemas']['DummyModel']
        | components['schemas']['MistralAiModel']
        | components['schemas']['OpenAiModel']
      settings: components['schemas']['ApiStrategySettings-Output']
    }
    /** ApiStrategySettings */
    'ApiStrategySettings-Input': {
      identity: components['schemas']['Identity'] | null
      /** Responsespecification */
      responseSpecification:
        | components['schemas']['JsonFromTextLlmResponseSpecification']
        | components['schemas']['JsonObjectLlmResponseSpecification']
        | components['schemas']['JsonSchemaLlmResponseSpecification']
      /** Systemprompt */
      systemPrompt: string
    }
    /** ApiStrategySettings */
    'ApiStrategySettings-Output': {
      identity: components['schemas']['Identity'] | null
      /** Responsespecification */
      responseSpecification:
        | components['schemas']['JsonFromTextLlmResponseSpecification']
        | components['schemas']['JsonObjectLlmResponseSpecification']
        | components['schemas']['JsonSchemaLlmResponseSpecification']
      /** Systemprompt */
      systemPrompt: string
    }
    /** ApiTextbook */
    ApiTextbook: {
      /** Createdby */
      createdBy: string
      /** Externalexercises */
      externalExercises: components['schemas']['ApiTextbookExternalExercise'][]
      /** Id */
      id: string
      /** Isbn */
      isbn: string | null
      /** Pages */
      pages: components['schemas']['patty__api_router__textbooks__ApiTextbook__Page'][]
      /** Publisher */
      publisher: string | null
      /** Ranges */
      ranges: components['schemas']['Range'][]
      /** Title */
      title: string
      /** Year */
      year: number | null
    }
    /** ApiTextbookAdaptableExercise */
    ApiTextbookAdaptableExercise: {
      adaptation: components['schemas']['ApiAdaptation']
      /** Exercisenumber */
      exerciseNumber: string
      /**
       * Kind
       * @constant
       */
      kind: 'adaptable'
      /** Pagenumber */
      pageNumber: number
    }
    /** ApiTextbookExternalExercise */
    ApiTextbookExternalExercise: {
      /** Exercisenumber */
      exerciseNumber: string
      /** Id */
      id: string
      /**
       * Kind
       * @constant
       */
      kind: 'external'
      /** Originalfilename */
      originalFileName: string
      /** Pagenumber */
      pageNumber: number
      /** Removedfromtextbook */
      removedFromTextbook: boolean
    }
    Arrow: {
      /**
       * Kind
       * @constant
       */
      kind: 'arrow'
    }
    /** BaseAdaptationBatch */
    BaseAdaptationBatch: {
      /** Availablestrategysettings */
      availableStrategySettings: components['schemas']['ApiStrategySettings-Output'][]
      /** Id */
      id: string
      /** Inputs */
      inputs: components['schemas']['ApiInput'][]
      strategy: components['schemas']['ApiStrategy-Output']
    }
    'Choice-Input': {
      /** Contents */
      contents: (
        | components['schemas']['Text']
        | components['schemas']['Whitespace']
        | components['schemas']['Arrow']
        | components['schemas']['Formatted-Input']
      )[]
      /**
       * Kind
       * @constant
       */
      kind: 'choice'
    }
    'Choice-Output': {
      /** Contents */
      contents: (
        | components['schemas']['Text']
        | components['schemas']['Whitespace']
        | components['schemas']['Arrow']
        | components['schemas']['Formatted-Output']
      )[]
      /**
       * Kind
       * @constant
       */
      kind: 'choice'
    }
    /** ClassificationBatch */
    ClassificationBatch: {
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string
      /** Createdby */
      createdBy: string | null
      /** Id */
      id: string
    }
    /** ClassificationInput */
    ClassificationInput: {
      /** Exercisenumber */
      exerciseNumber: string | null
      /** Instructionhintexampletext */
      instructionHintExampleText: string
      /** Pagenumber */
      pageNumber: number | null
      /** Statementtext */
      statementText: string
    }
    /** CreatePdfFileRequest */
    CreatePdfFileRequest: {
      /** Bytescount */
      bytesCount: number
      /** Creator */
      creator: string
      /** Filename */
      fileName: string
      /** Pagescount */
      pagesCount: number
      /** Sha256 */
      sha256: string
    }
    /** CreatePdfFileResponse */
    CreatePdfFileResponse: {
      /** Uploadurl */
      uploadUrl: string | null
    }
    /** DummyModel */
    DummyModel: {
      /**
       * Name
       * @enum {string}
       */
      name: 'dummy-1' | 'dummy-2' | 'dummy-3'
      /**
       * Provider
       * @constant
       */
      provider: 'dummy'
    }
    EditableTextInput: {
      /** Contents */
      contents: (components['schemas']['Text'] | components['schemas']['Whitespace'])[]
      /**
       * Increasehorizontalspace
       * @default false
       */
      increaseHorizontalSpace?: boolean
      /**
       * Kind
       * @constant
       */
      kind: 'editableTextInput'
      /** Showoriginaltext */
      showOriginalText: boolean
    }
    /** Error */
    Error: {
      /** Caughtby */
      caughtBy: string
      /** Codelocation */
      codeLocation: string | null
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string
      /** Createdby */
      createdBy: string | null
      /** Id */
      id: string
      /** Message */
      message: string
      /** Pattyversion */
      pattyVersion: string
      /** Url */
      url: string
      /** Useragent */
      userAgent: string
      /** Windowsize */
      windowSize: string
    }
    /** ExampleComponents */
    ExampleComponents: {
      /**
       * Arrow
       * @constant
       */
      arrow: true
      /**
       * Formatted
       * @constant
       */
      formatted: true
      /**
       * Text
       * @constant
       */
      text: true
      /**
       * Whitespace
       * @constant
       */
      whitespace: true
    }
    'ExerciseV1-Input': {
      example: components['schemas']['Page_Union_Text__Whitespace__Arrow__Formatted__-Input'] | null
      /**
       * Format
       * @constant
       */
      format: 'v1'
      hint: components['schemas']['Page_Union_Text__Whitespace__Arrow__Formatted__-Input'] | null
      instruction: components['schemas']['Page_Union_Text__Whitespace__Arrow__Formatted__Choice__-Input']
      reference: components['schemas']['Line_Union_Text__Whitespace__Arrow__Formatted__-Input'] | null
      statement: components['schemas']['Pages_Union_Text__Whitespace__Arrow__ActiveFormatted__FreeTextInput__MultipleChoicesInput__SelectableInput__SwappableInput__EditableTextInput__SplitWordInput__-Input']
    }
    'ExerciseV1-Output': {
      example: components['schemas']['Page_Union_Text__Whitespace__Arrow__Formatted__-Output'] | null
      /**
       * Format
       * @constant
       */
      format: 'v1'
      hint: components['schemas']['Page_Union_Text__Whitespace__Arrow__Formatted__-Output'] | null
      instruction: components['schemas']['Page_Union_Text__Whitespace__Arrow__Formatted__Choice__-Output']
      reference: components['schemas']['Line_Union_Text__Whitespace__Arrow__Formatted__-Output'] | null
      statement: components['schemas']['Pages_Union_Text__Whitespace__Arrow__ActiveFormatted__FreeTextInput__MultipleChoicesInput__SelectableInput__SwappableInput__EditableTextInput__SplitWordInput__-Output']
    }
    'ExerciseV2-Input': {
      /**
       * Format
       * @constant
       */
      format: 'v2'
      /** Phases */
      phases: components['schemas']['Phase-Input'][]
      reference: components['schemas']['Line_Union_Text__Whitespace__Arrow__Formatted__-Input'] | null
    }
    'ExerciseV2-Output': {
      /**
       * Format
       * @constant
       */
      format: 'v2'
      /** Phases */
      phases: components['schemas']['Phase-Output'][]
      reference: components['schemas']['Line_Union_Text__Whitespace__Arrow__Formatted__-Output'] | null
    }
    /** ExtractionBatch */
    ExtractionBatch: {
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string
      /** Createdby */
      createdBy: string
      /** Id */
      id: string
    }
    'Formatted-Input': {
      /**
       * Bold
       * @default false
       */
      bold?: boolean
      /**
       * Boxed
       * @default false
       */
      boxed?: boolean
      /** Contents */
      contents: (
        | components['schemas']['Text']
        | components['schemas']['Whitespace']
        | components['schemas']['Arrow']
        | components['schemas']['Formatted-Input']
      )[]
      /** Highlighted */
      highlighted?: string | null
      /**
       * Italic
       * @default false
       */
      italic?: boolean
      /**
       * Kind
       * @constant
       */
      kind: 'formatted'
      /**
       * Subscript
       * @default false
       */
      subscript?: boolean
      /**
       * Superscript
       * @default false
       */
      superscript?: boolean
      /**
       * Underlined
       * @default false
       */
      underlined?: boolean
    }
    'Formatted-Output': {
      /**
       * Bold
       * @default false
       */
      bold?: boolean
      /**
       * Boxed
       * @default false
       */
      boxed?: boolean
      /** Contents */
      contents: (
        | components['schemas']['Text']
        | components['schemas']['Whitespace']
        | components['schemas']['Arrow']
        | components['schemas']['Formatted-Output']
      )[]
      /** Highlighted */
      highlighted?: string | null
      /**
       * Italic
       * @default false
       */
      italic?: boolean
      /**
       * Kind
       * @constant
       */
      kind: 'formatted'
      /**
       * Subscript
       * @default false
       */
      subscript?: boolean
      /**
       * Superscript
       * @default false
       */
      superscript?: boolean
      /**
       * Underlined
       * @default false
       */
      underlined?: boolean
    }
    'FormattedTextContainer-Input': {
      /** Contents */
      contents: (
        | components['schemas']['Text']
        | components['schemas']['Whitespace']
        | components['schemas']['Arrow']
        | components['schemas']['Formatted-Input']
      )[]
    }
    'FormattedTextContainer-Output': {
      /** Contents */
      contents: (
        | components['schemas']['Text']
        | components['schemas']['Whitespace']
        | components['schemas']['Arrow']
        | components['schemas']['Formatted-Output']
      )[]
    }
    FreeTextInput: {
      /**
       * Kind
       * @constant
       */
      kind: 'freeTextInput'
    }
    /** GeminiModel */
    GeminiModel: {
      /**
       * Name
       * @constant
       */
      name: 'gemini-2.0-flash'
      /**
       * Provider
       * @constant
       */
      provider: 'gemini'
    }
    'GeneratedPages-Input': {
      generated: components['schemas']['Generator-Input']
    }
    'GeneratedPages-Output': {
      generated: components['schemas']['Generator-Output']
    }
    'Generator-Input': {
      items: components['schemas']['SelectableInputGeneratorItems']
      /** Itemsperpage */
      itemsPerPage: number
      template: components['schemas']['GeneratorTemplate-Input']
    }
    'Generator-Output': {
      items: components['schemas']['SelectableInputGeneratorItems']
      /** Itemsperpage */
      itemsPerPage: number
      template: components['schemas']['GeneratorTemplate-Output']
    }
    'GeneratorTemplate-Input': {
      /** Contents */
      contents: (
        | components['schemas']['Text']
        | components['schemas']['Whitespace']
        | components['schemas']['Arrow']
        | components['schemas']['ActiveFormatted-Input']
        | components['schemas']['FreeTextInput']
        | components['schemas']['MultipleChoicesInput-Input']
        | components['schemas']['SelectableInput-Input']
        | components['schemas']['SwappableInput-Input']
        | components['schemas']['EditableTextInput']
        | components['schemas']['SplitWordInput']
        | components['schemas']['GeneratorTemplatePlaceholder']
      )[]
    }
    'GeneratorTemplate-Output': {
      /** Contents */
      contents: (
        | components['schemas']['Text']
        | components['schemas']['Whitespace']
        | components['schemas']['Arrow']
        | components['schemas']['ActiveFormatted-Output']
        | components['schemas']['FreeTextInput']
        | components['schemas']['MultipleChoicesInput-Output']
        | components['schemas']['SelectableInput-Output']
        | components['schemas']['SwappableInput-Output']
        | components['schemas']['EditableTextInput']
        | components['schemas']['SplitWordInput']
        | components['schemas']['GeneratorTemplatePlaceholder']
      )[]
    }
    GeneratorTemplatePlaceholder: {
      /**
       * Kind
       * @constant
       */
      kind: 'itemPlaceholder'
    }
    /** GetAdaptationBatchResponse */
    GetAdaptationBatchResponse: {
      /** Adaptations */
      adaptations: components['schemas']['ApiAdaptation'][]
      /** Createdby */
      createdBy: string
      /** Id */
      id: string
      strategy: components['schemas']['ApiStrategy-Output']
    }
    /** GetAdaptationBatchesResponse */
    GetAdaptationBatchesResponse: {
      /** Adaptationbatches */
      adaptationBatches: components['schemas']['AdaptationBatch'][]
      /** Nextchunkid */
      nextChunkId: string | null
    }
    /** GetClassificationBatchResponse */
    GetClassificationBatchResponse: {
      /** Createdby */
      createdBy: string | null
      /** Exercises */
      exercises: components['schemas']['patty__api_router__sandbox_classification__GetClassificationBatchResponse__Exercise'][]
      /** Id */
      id: string
      /** Modelforadaptation */
      modelForAdaptation:
        | components['schemas']['DummyModel']
        | components['schemas']['MistralAiModel']
        | components['schemas']['OpenAiModel']
        | null
    }
    /** GetClassificationBatchesResponse */
    GetClassificationBatchesResponse: {
      /** Classificationbatches */
      classificationBatches: components['schemas']['ClassificationBatch'][]
      /** Nextchunkid */
      nextChunkId: string | null
    }
    /** GetErrorsCaughtByFrontendResponse */
    GetErrorsCaughtByFrontendResponse: {
      /** Errors */
      errors: components['schemas']['Error'][]
    }
    /** GetExtractionBatchResponse */
    GetExtractionBatchResponse: {
      /** Createdby */
      createdBy: string
      /** Id */
      id: string
      /** Modelforadaptation */
      modelForAdaptation:
        | components['schemas']['DummyModel']
        | components['schemas']['MistralAiModel']
        | components['schemas']['OpenAiModel']
        | null
      /** Pages */
      pages: components['schemas']['patty__api_router__sandbox_extraction__GetExtractionBatchResponse__Page'][]
      /** Runclassification */
      runClassification: boolean
      strategy: components['schemas']['ApiExtractionStrategy']
    }
    /** GetExtractionBatchesResponse */
    GetExtractionBatchesResponse: {
      /** Extractionbatches */
      extractionBatches: components['schemas']['ExtractionBatch'][]
      /** Nextchunkid */
      nextChunkId: string | null
    }
    /** GetTextbookResponse */
    GetTextbookResponse: {
      /** Availablestrategysettings */
      availableStrategySettings: string[]
      textbook: components['schemas']['ApiTextbook']
    }
    /** GetTextbooksResponse */
    GetTextbooksResponse: {
      /** Textbooks */
      textbooks: components['schemas']['Textbook'][]
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /** HintComponents */
    HintComponents: {
      /**
       * Arrow
       * @constant
       */
      arrow: true
      /**
       * Formatted
       * @constant
       */
      formatted: true
      /**
       * Text
       * @constant
       */
      text: true
      /**
       * Whitespace
       * @constant
       */
      whitespace: true
    }
    /** Identity */
    Identity: {
      /** Name */
      name: string
      /**
       * Version
       * @enum {string}
       */
      version: 'current' | 'previous' | 'older'
    }
    /** InstructionComponents */
    InstructionComponents: {
      /**
       * Arrow
       * @constant
       */
      arrow: true
      /** Choice */
      choice: boolean
      /**
       * Formatted
       * @constant
       */
      formatted: true
      /**
       * Text
       * @constant
       */
      text: true
      /**
       * Whitespace
       * @constant
       */
      whitespace: true
    }
    /** InvalidJsonError */
    InvalidJsonError: {
      /**
       * Error
       * @constant
       */
      error: 'invalid-json'
      /**
       * Kind
       * @constant
       */
      kind: 'error'
      /** Parsed */
      parsed: unknown
    }
    /** JsonFromTextLlmResponseSpecification */
    JsonFromTextLlmResponseSpecification: {
      /**
       * Formalism
       * @constant
       */
      formalism: 'text'
      /**
       * Format
       * @constant
       */
      format: 'json'
    }
    /** JsonObjectLlmResponseSpecification */
    JsonObjectLlmResponseSpecification: {
      /**
       * Formalism
       * @constant
       */
      formalism: 'json-object'
      /**
       * Format
       * @constant
       */
      format: 'json'
    }
    /** JsonSchemaLlmResponseSpecification */
    JsonSchemaLlmResponseSpecification: {
      exampleComponents: components['schemas']['ExampleComponents']
      /**
       * Formalism
       * @constant
       */
      formalism: 'json-schema'
      /**
       * Format
       * @constant
       */
      format: 'json'
      hintComponents: components['schemas']['HintComponents']
      instructionComponents: components['schemas']['InstructionComponents']
      referenceComponents: components['schemas']['ReferenceComponents']
      statementComponents: components['schemas']['StatementComponents']
    }
    'Line_Union_Text__Whitespace__Arrow__ActiveFormatted__FreeTextInput__MultipleChoicesInput__SelectableInput__SwappableInput__EditableTextInput__SplitWordInput__-Input': {
      /** Contents */
      contents: (
        | components['schemas']['Text']
        | components['schemas']['Whitespace']
        | components['schemas']['Arrow']
        | components['schemas']['ActiveFormatted-Input']
        | components['schemas']['FreeTextInput']
        | components['schemas']['MultipleChoicesInput-Input']
        | components['schemas']['SelectableInput-Input']
        | components['schemas']['SwappableInput-Input']
        | components['schemas']['EditableTextInput']
        | components['schemas']['SplitWordInput']
      )[]
    }
    'Line_Union_Text__Whitespace__Arrow__ActiveFormatted__FreeTextInput__MultipleChoicesInput__SelectableInput__SwappableInput__EditableTextInput__SplitWordInput__-Output': {
      /** Contents */
      contents: (
        | components['schemas']['Text']
        | components['schemas']['Whitespace']
        | components['schemas']['Arrow']
        | components['schemas']['ActiveFormatted-Output']
        | components['schemas']['FreeTextInput']
        | components['schemas']['MultipleChoicesInput-Output']
        | components['schemas']['SelectableInput-Output']
        | components['schemas']['SwappableInput-Output']
        | components['schemas']['EditableTextInput']
        | components['schemas']['SplitWordInput']
      )[]
    }
    'Line_Union_Text__Whitespace__Arrow__Formatted__-Input': {
      /** Contents */
      contents: (
        | components['schemas']['Text']
        | components['schemas']['Whitespace']
        | components['schemas']['Arrow']
        | components['schemas']['Formatted-Input']
      )[]
    }
    'Line_Union_Text__Whitespace__Arrow__Formatted__-Output': {
      /** Contents */
      contents: (
        | components['schemas']['Text']
        | components['schemas']['Whitespace']
        | components['schemas']['Arrow']
        | components['schemas']['Formatted-Output']
      )[]
    }
    'Line_Union_Text__Whitespace__Arrow__Formatted__Choice__-Input': {
      /** Contents */
      contents: (
        | components['schemas']['Text']
        | components['schemas']['Whitespace']
        | components['schemas']['Arrow']
        | components['schemas']['Formatted-Input']
        | components['schemas']['Choice-Input']
      )[]
    }
    'Line_Union_Text__Whitespace__Arrow__Formatted__Choice__-Output': {
      /** Contents */
      contents: (
        | components['schemas']['Text']
        | components['schemas']['Whitespace']
        | components['schemas']['Arrow']
        | components['schemas']['Formatted-Output']
        | components['schemas']['Choice-Output']
      )[]
    }
    /** MistralAiModel */
    MistralAiModel: {
      /**
       * Name
       * @enum {string}
       */
      name: 'mistral-large-2411' | 'mistral-small-2501'
      /**
       * Provider
       * @constant
       */
      provider: 'mistralai'
    }
    'MultipleChoicesInput-Input': {
      /** Choices */
      choices: components['schemas']['FormattedTextContainer-Input'][]
      /**
       * Kind
       * @constant
       */
      kind: 'multipleChoicesInput'
      /** Showchoicesbydefault */
      showChoicesByDefault: boolean
    }
    'MultipleChoicesInput-Output': {
      /** Choices */
      choices: components['schemas']['FormattedTextContainer-Output'][]
      /**
       * Kind
       * @constant
       */
      kind: 'multipleChoicesInput'
      /** Showchoicesbydefault */
      showChoicesByDefault: boolean
    }
    /** NotJsonError */
    NotJsonError: {
      /**
       * Error
       * @constant
       */
      error: 'not-json'
      /**
       * Kind
       * @constant
       */
      kind: 'error'
      /** Text */
      text: string
    }
    /** OpenAiModel */
    OpenAiModel: {
      /**
       * Name
       * @enum {string}
       */
      name: 'gpt-4o-2024-08-06' | 'gpt-4o-mini-2024-07-18'
      /**
       * Provider
       * @constant
       */
      provider: 'openai'
    }
    'Page_Union_Text__Whitespace__Arrow__ActiveFormatted__FreeTextInput__MultipleChoicesInput__SelectableInput__SwappableInput__EditableTextInput__SplitWordInput__-Input': {
      /** Lines */
      lines: components['schemas']['Line_Union_Text__Whitespace__Arrow__ActiveFormatted__FreeTextInput__MultipleChoicesInput__SelectableInput__SwappableInput__EditableTextInput__SplitWordInput__-Input'][]
    }
    'Page_Union_Text__Whitespace__Arrow__ActiveFormatted__FreeTextInput__MultipleChoicesInput__SelectableInput__SwappableInput__EditableTextInput__SplitWordInput__-Output': {
      /** Lines */
      lines: components['schemas']['Line_Union_Text__Whitespace__Arrow__ActiveFormatted__FreeTextInput__MultipleChoicesInput__SelectableInput__SwappableInput__EditableTextInput__SplitWordInput__-Output'][]
    }
    'Page_Union_Text__Whitespace__Arrow__Formatted__-Input': {
      /** Lines */
      lines: components['schemas']['Line_Union_Text__Whitespace__Arrow__Formatted__-Input'][]
    }
    'Page_Union_Text__Whitespace__Arrow__Formatted__-Output': {
      /** Lines */
      lines: components['schemas']['Line_Union_Text__Whitespace__Arrow__Formatted__-Output'][]
    }
    'Page_Union_Text__Whitespace__Arrow__Formatted__Choice__-Input': {
      /** Lines */
      lines: components['schemas']['Line_Union_Text__Whitespace__Arrow__Formatted__Choice__-Input'][]
    }
    'Page_Union_Text__Whitespace__Arrow__Formatted__Choice__-Output': {
      /** Lines */
      lines: components['schemas']['Line_Union_Text__Whitespace__Arrow__Formatted__Choice__-Output'][]
    }
    'Pages_Union_Text__Whitespace__Arrow__ActiveFormatted__FreeTextInput__MultipleChoicesInput__SelectableInput__SwappableInput__EditableTextInput__SplitWordInput__-Input': {
      /** Pages */
      pages: components['schemas']['Page_Union_Text__Whitespace__Arrow__ActiveFormatted__FreeTextInput__MultipleChoicesInput__SelectableInput__SwappableInput__EditableTextInput__SplitWordInput__-Input'][]
    }
    'Pages_Union_Text__Whitespace__Arrow__ActiveFormatted__FreeTextInput__MultipleChoicesInput__SelectableInput__SwappableInput__EditableTextInput__SplitWordInput__-Output': {
      /** Pages */
      pages: components['schemas']['Page_Union_Text__Whitespace__Arrow__ActiveFormatted__FreeTextInput__MultipleChoicesInput__SelectableInput__SwappableInput__EditableTextInput__SplitWordInput__-Output'][]
    }
    'Phase-Input': {
      example: components['schemas']['Page_Union_Text__Whitespace__Arrow__Formatted__-Input'] | null
      hint: components['schemas']['Page_Union_Text__Whitespace__Arrow__Formatted__-Input'] | null
      instruction: components['schemas']['Page_Union_Text__Whitespace__Arrow__Formatted__Choice__-Input']
      /** Statement */
      statement:
        | components['schemas']['Pages_Union_Text__Whitespace__Arrow__ActiveFormatted__FreeTextInput__MultipleChoicesInput__SelectableInput__SwappableInput__EditableTextInput__SplitWordInput__-Input']
        | components['schemas']['GeneratedPages-Input']
    }
    'Phase-Output': {
      example: components['schemas']['Page_Union_Text__Whitespace__Arrow__Formatted__-Output'] | null
      hint: components['schemas']['Page_Union_Text__Whitespace__Arrow__Formatted__-Output'] | null
      instruction: components['schemas']['Page_Union_Text__Whitespace__Arrow__Formatted__Choice__-Output']
      /** Statement */
      statement:
        | components['schemas']['Pages_Union_Text__Whitespace__Arrow__ActiveFormatted__FreeTextInput__MultipleChoicesInput__SelectableInput__SwappableInput__EditableTextInput__SplitWordInput__-Output']
        | components['schemas']['GeneratedPages-Output']
    }
    /** PostAdaptationAdjustmentRequest */
    PostAdaptationAdjustmentRequest: {
      /** Adjustment */
      adjustment: string
    }
    /** PostAdaptationBatchRequest */
    PostAdaptationBatchRequest: {
      /** Creator */
      creator: string
      /** Inputs */
      inputs: components['schemas']['ApiInput'][]
      strategy: components['schemas']['ApiStrategy-Input']
    }
    /** PostAdaptationBatchResponse */
    PostAdaptationBatchResponse: {
      /** Id */
      id: string
    }
    /** PostClassificationBatchRequest */
    PostClassificationBatchRequest: {
      /** Creator */
      creator: string
      /** Inputs */
      inputs: components['schemas']['ClassificationInput'][]
      /** Modelforadaptation */
      modelForAdaptation:
        | components['schemas']['DummyModel']
        | components['schemas']['MistralAiModel']
        | components['schemas']['OpenAiModel']
        | null
    }
    /** PostClassificationBatchResponse */
    PostClassificationBatchResponse: {
      /** Id */
      id: string
    }
    /** PostErrorsCaughtByFrontendRequest */
    PostErrorsCaughtByFrontendRequest: {
      /** Caughtby */
      caughtBy: string
      /** Codelocation */
      codeLocation: string | null
      /** Creator */
      creator: string | null
      /** Message */
      message: string
      /** Url */
      url: string
      /** Useragent */
      userAgent: string
      /** Windowsize */
      windowSize: string
    }
    /** PostErrorsCaughtByFrontendResponse */
    PostErrorsCaughtByFrontendResponse: Record<string, never>
    /** PostExtractionBatchRequest */
    PostExtractionBatchRequest: {
      /** Creator */
      creator: string
      /** Firstpage */
      firstPage: number
      /** Modelforadaptation */
      modelForAdaptation:
        | components['schemas']['DummyModel']
        | components['schemas']['MistralAiModel']
        | components['schemas']['OpenAiModel']
        | null
      /** Pagescount */
      pagesCount: number
      /** Pdffilesha256 */
      pdfFileSha256: string
      /** Runclassification */
      runClassification: boolean
      strategy: components['schemas']['ApiExtractionStrategy']
    }
    /** PostExtractionBatchResponse */
    PostExtractionBatchResponse: {
      /** Id */
      id: string
    }
    /** PostTextbookExternalExercisesRequest */
    PostTextbookExternalExercisesRequest: {
      /** Creator */
      creator: string
      /** Exercisenumber */
      exerciseNumber: string
      /** Originalfilename */
      originalFileName: string
      /** Pagenumber */
      pageNumber: number
    }
    /** PostTextbookExternalExercisesResponse */
    PostTextbookExternalExercisesResponse: {
      /** Puturl */
      putUrl: string
    }
    /** PostTextbookRangeRequest */
    PostTextbookRangeRequest: {
      /** Creator */
      creator: string
      /** Modelforadaptation */
      modelForAdaptation:
        | components['schemas']['DummyModel']
        | components['schemas']['MistralAiModel']
        | components['schemas']['OpenAiModel']
      /** Modelforextraction */
      modelForExtraction: components['schemas']['DummyModel'] | components['schemas']['GeminiModel']
      /** Pagescount */
      pagesCount: number
      /** Pdffilesha256 */
      pdfFileSha256: string
      /** Pdffirstpagenumber */
      pdfFirstPageNumber: number
      /** Textbookfirstpagenumber */
      textbookFirstPageNumber: number
    }
    /** PostTextbookRequest */
    PostTextbookRequest: {
      /** Creator */
      creator: string
      /** Isbn */
      isbn: string | null
      /** Publisher */
      publisher: string | null
      /** Title */
      title: string
      /** Year */
      year: number | null
    }
    /** PostTextbookResponse */
    PostTextbookResponse: {
      /** Id */
      id: string
    }
    /** PostTokenRequest */
    PostTokenRequest: {
      /** Password */
      password: string
      /**
       * Validity
       * Format: duration
       * @default PT3H
       */
      validity?: string
    }
    /** PostTokenResponse */
    PostTokenResponse: {
      /** Accesstoken */
      accessToken: string
      /**
       * Tokentype
       * @default bearer
       */
      tokenType?: string
      /**
       * Validuntil
       * Format: date-time
       */
      validUntil: string
    }
    /** PutAdaptableExerciseClassRequest */
    PutAdaptableExerciseClassRequest: {
      /** Classname */
      className: string
      /** Creator */
      creator: string
    }
    /** Range */
    Range: {
      /** Id */
      id: string
      /** Modelforadaptation */
      modelForAdaptation:
        | components['schemas']['DummyModel']
        | components['schemas']['MistralAiModel']
        | components['schemas']['OpenAiModel']
      /** Modelforextraction */
      modelForExtraction: components['schemas']['DummyModel'] | components['schemas']['GeminiModel']
      /** Pages */
      pages: components['schemas']['patty__api_router__textbooks__ApiTextbook__Range__Page'][]
      /** Pagescount */
      pagesCount: number
      /** Pdffilenames */
      pdfFileNames: string[]
      /** Pdffilesha256 */
      pdfFileSha256: string
      /** Pdffirstpagenumber */
      pdfFirstPageNumber: number
      /** Removedfromtextbook */
      removedFromTextbook: boolean
      /** Textbookfirstpagenumber */
      textbookFirstPageNumber: number
    }
    /** ReferenceComponents */
    ReferenceComponents: {
      /**
       * Arrow
       * @constant
       */
      arrow: true
      /**
       * Formatted
       * @constant
       */
      formatted: true
      /**
       * Text
       * @constant
       */
      text: true
      /**
       * Whitespace
       * @constant
       */
      whitespace: true
    }
    /** RootModel[Union[ExerciseV1, ExerciseV2]] */
    'RootModel_Union_ExerciseV1__ExerciseV2__-Input':
      | components['schemas']['ExerciseV1-Input']
      | components['schemas']['ExerciseV2-Input']
    /** RootModel[Union[ExerciseV1, ExerciseV2]] */
    'RootModel_Union_ExerciseV1__ExerciseV2__-Output':
      | components['schemas']['ExerciseV1-Output']
      | components['schemas']['ExerciseV2-Output']
    'SelectableInput-Input': {
      /** Boxed */
      boxed: boolean
      /** Colors */
      colors: string[]
      /** Contents */
      contents: (
        | components['schemas']['Text']
        | components['schemas']['Whitespace']
        | components['schemas']['Arrow']
        | components['schemas']['Formatted-Input']
        | components['schemas']['SelectableInput-Input']
      )[]
      /**
       * Kind
       * @constant
       */
      kind: 'selectableInput'
    }
    'SelectableInput-Output': {
      /** Boxed */
      boxed: boolean
      /** Colors */
      colors: string[]
      /** Contents */
      contents: (
        | components['schemas']['Text']
        | components['schemas']['Whitespace']
        | components['schemas']['Arrow']
        | components['schemas']['Formatted-Output']
        | components['schemas']['SelectableInput-Output']
      )[]
      /**
       * Kind
       * @constant
       */
      kind: 'selectableInput'
    }
    SelectableInputGeneratorItems: {
      /** Colorindex */
      colorIndex: number
      /**
       * Kind
       * @constant
       */
      kind: 'selectableInput'
    }
    SplitWordInput: {
      /**
       * Kind
       * @constant
       */
      kind: 'splitWordInput'
      /** Word */
      word: string
    }
    /** StatementComponents */
    StatementComponents: {
      /**
       * Arrow
       * @constant
       */
      arrow: true
      /** Editabletextinput */
      editableTextInput: boolean
      /**
       * Formatted
       * @constant
       */
      formatted: true
      /** Freetextinput */
      freeTextInput: boolean
      /** Multiplechoicesinput */
      multipleChoicesInput: boolean
      /** Selectableinput */
      selectableInput: boolean
      /** Splitwordinput */
      splitWordInput: boolean
      /** Swappableinput */
      swappableInput: boolean
      /**
       * Text
       * @constant
       */
      text: true
      /**
       * Whitespace
       * @constant
       */
      whitespace: true
    }
    'SwappableInput-Input': {
      /** Contents */
      contents: (
        | components['schemas']['Text']
        | components['schemas']['Whitespace']
        | components['schemas']['Arrow']
        | components['schemas']['Formatted-Input']
      )[]
      /**
       * Kind
       * @constant
       */
      kind: 'swappableInput'
    }
    'SwappableInput-Output': {
      /** Contents */
      contents: (
        | components['schemas']['Text']
        | components['schemas']['Whitespace']
        | components['schemas']['Arrow']
        | components['schemas']['Formatted-Output']
      )[]
      /**
       * Kind
       * @constant
       */
      kind: 'swappableInput'
    }
    Text: {
      /**
       * Kind
       * @constant
       */
      kind: 'text'
      /** Text */
      text: string
    }
    /** Textbook */
    Textbook: {
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string
      /** Createdby */
      createdBy: string
      /** Id */
      id: string
      /** Publisher */
      publisher: string | null
      /** Title */
      title: string
      /** Year */
      year: number | null
    }
    /** UnknownError */
    UnknownError: {
      /**
       * Error
       * @constant
       */
      error: 'unknown'
      /**
       * Kind
       * @constant
       */
      kind: 'error'
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
    }
    Whitespace: {
      /**
       * Kind
       * @constant
       */
      kind: 'whitespace'
    }
    /** Success */
    patty__adaptation__assistant_responses__Success: {
      exercise: components['schemas']['RootModel_Union_ExerciseV1__ExerciseV2__-Output']
      /**
       * Kind
       * @constant
       */
      kind: 'success'
    }
    /** Exercise */
    patty__api_router__sandbox_classification__GetClassificationBatchResponse__Exercise: {
      adaptation: components['schemas']['ApiAdaptation'] | null
      /** Exerciseclass */
      exerciseClass: string | null
      /** Exerciseclasshassettings */
      exerciseClassHasSettings: boolean
      /** Exercisenumber */
      exerciseNumber: string | null
      /** Fulltext */
      fullText: string
      /** Id */
      id: string
      /** Pagenumber */
      pageNumber: number | null
      /** Reclassifiedby */
      reclassifiedBy: string | null
    }
    /** Page */
    patty__api_router__sandbox_extraction__GetExtractionBatchResponse__Page: {
      /** Assistantresponse */
      assistantResponse:
        | components['schemas']['patty__extraction__assistant_responses__Success']
        | components['schemas']['InvalidJsonError']
        | components['schemas']['NotJsonError']
        | components['schemas']['UnknownError']
        | null
      /** Exercises */
      exercises: components['schemas']['patty__api_router__sandbox_extraction__GetExtractionBatchResponse__Page__Exercise'][]
      /** Pagenumber */
      pageNumber: number
    }
    /** Exercise */
    patty__api_router__sandbox_extraction__GetExtractionBatchResponse__Page__Exercise: {
      adaptation: components['schemas']['ApiAdaptation'] | null
      /** Exerciseclass */
      exerciseClass: string | null
      /** Exerciseclasshassettings */
      exerciseClassHasSettings: boolean
      /** Exercisenumber */
      exerciseNumber: string | null
      /** Fulltext */
      fullText: string
      /** Id */
      id: string
      /** Pagenumber */
      pageNumber: number | null
      /** Reclassifiedby */
      reclassifiedBy: string | null
    }
    /** Page */
    patty__api_router__textbooks__ApiTextbook__Page: {
      /** Exercises */
      exercises: (
        | components['schemas']['ApiTextbookAdaptableExercise']
        | components['schemas']['ApiTextbookExternalExercise']
      )[]
      /** Number */
      number: number
    }
    /** Page */
    patty__api_router__textbooks__ApiTextbook__Range__Page: {
      /** Exercises */
      exercises: components['schemas']['patty__api_router__textbooks__ApiTextbook__Range__Page__Exercise'][]
      /** Inprogress */
      inProgress: boolean
      /** Pagenumber */
      pageNumber: number
    }
    /** Exercise */
    patty__api_router__textbooks__ApiTextbook__Range__Page__Exercise: {
      adaptation: components['schemas']['ApiAdaptation'] | null
      /** Exerciseclass */
      exerciseClass: string | null
      /** Exerciseclasshassettings */
      exerciseClassHasSettings: boolean
      /** Exercisenumber */
      exerciseNumber: string
      /** Fulltext */
      fullText: string
      /** Id */
      id: string
      /** Pagenumber */
      pageNumber: number
      /** Reclassifiedby */
      reclassifiedBy: null
      /** Removedfromtextbook */
      removedFromTextbook: boolean
    }
    /** Success */
    patty__extraction__assistant_responses__Success: {
      /** Exercises */
      exercises: components['schemas']['patty__extraction__extracted__Exercise'][]
      /**
       * Kind
       * @constant
       */
      kind: 'success'
    }
    /** Exercise */
    patty__extraction__extracted__Exercise: {
      /** Autre */
      autre?: string | null
      /** Conseil */
      conseil?: string | null
      /**
       * Consignes
       * @default []
       */
      consignes?: string[]
      /** Enonce */
      enonce?: string | null
      /** Exemple */
      exemple?: string | null
      /** Id */
      id?: string | null
      /** Numero */
      numero?: string | null
      /** References */
      references?: string | null
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  put_adaptable_exercise_class_api_adaptable_exercises__id__exercise_class_put: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PutAdaptableExerciseClassRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_adaptation_batches_api_adaptation_batches_get: {
    parameters: {
      query?: {
        chunkId?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GetAdaptationBatchesResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  post_adaptation_batch_api_adaptation_batches_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PostAdaptationBatchRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PostAdaptationBatchResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_adaptation_batch_api_adaptation_batches__id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GetAdaptationBatchResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  make_adaptation_llm_response_schema_api_adaptation_llm_response_schema_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['JsonSchemaLlmResponseSpecification']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': Record<string, never>
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_adaptation_api_adaptations__id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiAdaptation']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  post_adaptation_adjustment_api_adaptations__id__adjustment_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PostAdaptationAdjustmentRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiAdaptation']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_adaptation_last_adjustment_api_adaptations__id__last_adjustment_delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiAdaptation']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  put_adaptation_manual_edit_api_adaptations__id__manual_edit_put: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RootModel_Union_ExerciseV1__ExerciseV2__-Input']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiAdaptation']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_adaptation_manual_edit_api_adaptations__id__manual_edit_delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiAdaptation']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_available_adaptation_llm_models_api_available_adaptation_llm_models_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': (
            | components['schemas']['DummyModel']
            | components['schemas']['MistralAiModel']
            | components['schemas']['OpenAiModel']
          )[]
        }
      }
    }
  }
  get_available_extraction_llm_models_api_available_extraction_llm_models_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': (components['schemas']['DummyModel'] | components['schemas']['GeminiModel'])[]
        }
      }
    }
  }
  get_base_adaptation_batch_api_base_adaptation_batch_get: {
    parameters: {
      query: {
        user: string
        base?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BaseAdaptationBatch']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_classification_batches_api_classification_batches_get: {
    parameters: {
      query?: {
        chunkId?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GetClassificationBatchesResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_classification_batch_api_classification_batches_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PostClassificationBatchRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PostClassificationBatchResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_classification_batch_api_classification_batches__id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GetClassificationBatchResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  put_classification_batch_model_for_adaptation_api_classification_batches__id__model_for_adaptation_put: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json':
          | components['schemas']['DummyModel']
          | components['schemas']['MistralAiModel']
          | components['schemas']['OpenAiModel']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  submit_adaptations_with_recent_settings_in_classification_batch_api_classification_batches__id__submit_adaptations_with_recent_settings_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  retrieve_errors_api_errors_caught_by_frontend_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GetErrorsCaughtByFrontendResponse']
        }
      }
    }
  }
  create_error_api_errors_caught_by_frontend_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PostErrorsCaughtByFrontendRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PostErrorsCaughtByFrontendResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_exercise_classes_api_exercise_classes_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': string[]
        }
      }
    }
  }
  get_extraction_batches_api_extraction_batches_get: {
    parameters: {
      query?: {
        chunkId?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GetExtractionBatchesResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_extraction_batch_api_extraction_batches_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PostExtractionBatchRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PostExtractionBatchResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_extraction_batch_api_extraction_batches__id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GetExtractionBatchResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  put_extraction_batch_model_for_adaptation_api_extraction_batches__id__model_for_adaptation_put: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json':
          | components['schemas']['DummyModel']
          | components['schemas']['MistralAiModel']
          | components['schemas']['OpenAiModel']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  put_extraction_batch_run_classification_api_extraction_batches__id__run_classification_put: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  submit_adaptations_with_recent_settings_in_extraction_batch_api_extraction_batches__id__submit_adaptations_with_recent_settings_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_extraction_llm_response_schema_api_extraction_llm_response_schema_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': Record<string, never>
        }
      }
    }
  }
  get_latest_extraction_strategy_api_latest_extraction_strategy_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiExtractionStrategy']
        }
      }
    }
  }
  create_pdf_file_api_pdf_files_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreatePdfFileRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CreatePdfFileResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_textbooks_api_textbooks_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GetTextbooksResponse']
        }
      }
    }
  }
  post_textbook_api_textbooks_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PostTextbookRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PostTextbookResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_textbook_api_textbooks__id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GetTextbookResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  post_textbook_range_api_textbooks__id__ranges_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PostTextbookRangeRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  put_textbook_exercises_removed_api_textbooks__textbook_id__exercises__exercise_id__removed_put: {
    parameters: {
      query: {
        removed: boolean
      }
      header?: never
      path: {
        textbook_id: string
        exercise_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiTextbook']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  post_textbook_external_exercises_api_textbooks__textbook_id__external_exercises_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        textbook_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PostTextbookExternalExercisesRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PostTextbookExternalExercisesResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  put_textbook_ranges_removed_api_textbooks__textbook_id__ranges__range_id__removed_put: {
    parameters: {
      query: {
        removed: boolean
      }
      header?: never
      path: {
        textbook_id: string
        range_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiTextbook']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  login_api_token_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PostTokenRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PostTokenResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
}
