// Copyright 2025 Vincent Jacques <vincent@vincent-jacques.net>

const ClassificationCamembert20250520 = {
  fileName: 'classification_camembert.pt',
  providedBy: 'Elise',
  providedOn: new Date('2025-05-20'),
  classesProduced: [
    'Associe',
    'AssocieCoche',
    'CM',
    'CacheIntrus',
    'Classe',
    'ClasseCM',
    'CliqueEcrire',
    'CocheGroupeMots',
    'CocheIntrus',
    'CocheLettre',
    'CocheMot',
    'CocheMot*',
    'CochePhrase',
    'Echange',
    'EditPhrase',
    'EditTexte',
    'ExpressionEcrite',
    'GenreNombre',
    'Phrases',
    'Question',
    'RC',
    'RCCadre',
    'RCDouble',
    'RCImage',
    'Texte',
    'Trait',
    'TransformeMot',
    'TransformePhrase',
    'VraiFaux',
  ],
}

export default ClassificationCamembert20250520
