from .adaptation import (
    OldAdaptation,
    OldBatch,
    OldExternalExercise,
    OldInput,
    OldStrategy,
    OldStrategySettings,
    OldStrategySettingsBranch,
    OldTextbook,
)
from .adaptation.orm_models import (
    AdaptableExercise,
    Adaptation,
    AdaptationBatch,
    AdaptationStrategy,
    AdaptationStrategySettings,
    BaseExercise,
    Classification,
    ClassificationStrategy,
    ExerciseClass,
    ExternalExercise,
    Extraction,
    ExtractionStrategy,
    PdfFile,
    Textbook,
    TextbookRange,
)
from .database_utils import OrmBase


__all__ = [
    "AdaptableExercise",
    "Adaptation",
    "AdaptationBatch",
    "AdaptationStrategy",
    "AdaptationStrategySettings",
    "BaseExercise",
    "Classification",
    "ClassificationStrategy",
    "ExerciseClass",
    "ExternalExercise",
    "Extraction",
    "ExtractionStrategy",
    "OldAdaptation",
    "OldBatch",
    "OldExternalExercise",
    "OldInput",
    "OldStrategy",
    "OldStrategySettings",
    "OldStrategySettingsBranch",
    "OldTextbook",
    "PdfFile",
    "Textbook",
    "TextbookRange",
]


all_models: list[type[OrmBase]] = [
    AdaptableExercise,
    Adaptation,
    AdaptationBatch,
    AdaptationStrategy,
    AdaptationStrategySettings,
    BaseExercise,
    Classification,
    ClassificationStrategy,
    ExerciseClass,
    ExternalExercise,
    Extraction,
    ExtractionStrategy,
    OldAdaptation,
    OldBatch,
    OldExternalExercise,
    OldInput,
    OldStrategy,
    OldStrategySettings,
    OldStrategySettingsBranch,
    OldTextbook,
    PdfFile,
    Textbook,
    TextbookRange,
]
