import datetime
import os

import pydantic


# This file can be used as a reference for required environment variables

assert "AWS_ACCESS_KEY_ID" in os.environ
assert "AWS_SECRET_ACCESS_KEY" in os.environ

MISTRALAI_API_KEY = os.environ["PATTY_MISTRALAI_API_KEY"]
OPENAI_API_KEY = os.environ["PATTY_OPENAI_API_KEY"]
GEMINIAI_KEY = os.environ["PATTY_GEMINIAI_KEY"]

INVESTIGATING_ISSUE_129 = os.environ.get("PATTY_INVESTIGATING_ISSUE_129", "false") == "true"

DATABASE_URL = os.environ["PATTY_DATABASE_URL"]
DATABASE_BACKUPS_URL = os.environ["PATTY_DATABASE_BACKUPS_URL"]
assert not DATABASE_BACKUPS_URL.endswith("/")
DATABASE_BACKUP_PULSE_MONITORING_URL = os.environ.get("PATTY_DATABASE_BACKUP_PULSE_MONITORING_URL")
assert DATABASE_BACKUP_PULSE_MONITORING_URL != ""
SUBMISSION_DAEMON_PULSE_MONITORING_URL = os.environ.get("PATTY_SUBMISSION_DAEMON_PULSE_MONITORING_URL")
assert SUBMISSION_DAEMON_PULSE_MONITORING_URL != ""
CLASSIFICATION_CAMEMBERT_2025_05_20_PATH = os.environ["PATTY_2025_05_20_CLASSIFICATION_CAMEMBERT_PT_PATH"]
IMAGES_DETECTION_MODEL_2025_09_15_PATH = os.environ["PATTY_2025_09_15_IMAGES_DETECTION_PT_PATH"]
DETECTED_IMAGES_SAVE_PATH = os.environ.get("PATTY_DETECTED_IMAGES_SAVE_PATH")
SECRET_JWT_KEY = os.environ["PATTY_SECRET_JWT_KEY"]
# Hashed password can be generated with 'python -m patty hash-password <password>'
HASHED_PASSWORD = os.environ["PATTY_HASHED_PASSWORD"]
AUTHENTICATION_MAX_VALIDITY = (
    pydantic.RootModel[datetime.timedelta].model_validate(os.environ["PATTY_AUTHENTICATION_MAX_VALIDITY"]).root
)
EXTERNAL_EXERCISES_URL = os.environ["PATTY_EXTERNAL_EXERCISES_URL"]
assert not EXTERNAL_EXERCISES_URL.endswith("/")
PDF_FILES_URL = os.environ["PATTY_PDF_FILES_URL"]
assert not PDF_FILES_URL.endswith("/")
EXERCISE_IMAGES_URL = os.environ["PATTY_EXERCISE_IMAGES_URL"]
assert not EXERCISE_IMAGES_URL.endswith("/")

MAIL_SENDER = os.environ["PATTY_MAIL_SENDER"]
SMTP_HOST = os.environ["PATTY_SMTP_HOST"]
SMTP_PORT = int(os.environ["PATTY_SMTP_PORT"])
SMTP_USER = os.environ["PATTY_SMTP_USER"]
SMTP_PASSWORD = os.environ["PATTY_SMTP_PASSWORD"]
