import datetime
import os

import pydantic


DATABASE_URL = os.environ["PATTY_DATABASE_URL"]
DATABASE_BACKUPS_URL = os.environ["PATTY_DATABASE_BACKUPS_URL"]
assert not DATABASE_BACKUPS_URL.endswith("/")
DATABASE_BACKUP_PULSE_MONITORING_URL = os.environ["PATTY_DATABASE_BACKUP_PULSE_MONITORING_URL"]
SUBMISSION_DAEMON_PULSE_MONITORING_URL = os.environ["PATTY_SUBMISSION_DAEMON_PULSE_MONITORING_URL"]
CLASSIFICATION_CAMEMBERT_2025_05_20_URL = os.environ["PATTY_2025_05_20_CLASSIFICATION_CAMEMBERT_PT_URL"]
CLASSIFICATION_MODELS_DIRECTORY_PATH = os.environ["PATTY_CLASSIFICATION_MODELS_DIRECTORY_PATH"]
IMAGES_DETECTION_MODEL_2025_09_15_URL = os.environ["PATTY_2025_09_15_IMAGES_DETECTION_PT_URL"]
IMAGES_DETECTION_MODELS_DIRECTORY_PATH = os.environ["PATTY_IMAGES_DETECTION_MODELS_DIRECTORY_PATH"]
DETECTED_IMAGES_SAVE_PATH = os.environ.get("PATTY_DETECTED_IMAGES_SAVE_PATH")
SECRET_JWT_KEY = os.environ["PATTY_SECRET_JWT_KEY"]
# Hashed password can be generated with 'python -m patty hash-password <password>'
HASHED_PASSWORD = os.environ["PATTY_HASHED_PASSWORD"]
AUTHENTICATION_MAX_VALIDITY = (
    pydantic.RootModel[datetime.timedelta].model_validate(os.environ["PATTY_AUTHENTICATION_MAX_VALIDITY"]).root
)
EXTERNAL_EXERCISES_URL = os.environ["PATTY_EXTERNAL_EXERCISES_URL"]
assert EXTERNAL_EXERCISES_URL.startswith("s3://")
assert not EXTERNAL_EXERCISES_URL.endswith("/")
PDF_FILES_URL = os.environ["PATTY_PDF_FILES_URL"]
assert PDF_FILES_URL.startswith("s3://")
assert not PDF_FILES_URL.endswith("/")
EXERCISE_IMAGES_URL = os.environ["PATTY_EXERCISE_IMAGES_URL"]
assert EXERCISE_IMAGES_URL.startswith("s3://")
assert not EXERCISE_IMAGES_URL.endswith("/")

MAIL_SENDER = os.environ["PATTY_MAIL_SENDER"]
SMTP_HOST = os.environ["PATTY_SMTP_HOST"]
SMTP_PORT = int(os.environ["PATTY_SMTP_PORT"])
SMTP_USER = os.environ["PATTY_SMTP_USER"]
SMTP_PASSWORD = os.environ["PATTY_SMTP_PASSWORD"]
