name: patty-prod-preview

services:
  # Actual prod services
  ######################

  backend:
    image: jacquev6/patty:preview-backend
    pull_policy: never
    env_file:
      - secrets.env

  frontend:
    image: jacquev6/patty:preview-frontend
    pull_policy: never

  # Preview-only services
  #######################

  fanout:
    image: nginx:latest
    ports:
      - 8090:8090
    volumes:
      - ./fanout/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
