<script setup lang="ts">
import { onMounted } from 'vue'
import { useI18n } from 'vue-i18n'

import ExamplesViewExercise, { type Example } from './AdaptedExerciseExamplesViewExercise.vue'
import { useBreadcrumbsStore } from './BreadcrumbsStore'

const breadcrumbsStore = useBreadcrumbsStore()
const { t } = useI18n()

onMounted(() => {
  breadcrumbsStore.set([{ textKey: 'sandbox' }, { textKey: 'adaptedExerciseExamples', to: {} }])
})

const yellow = '#ffff00'
const orange = '#ffcf4c'
const red = '#ff8084'
const pink = '#ffc0cb'
const purple = '#d49cff'
const darkBlue = '#8177ff'
const lightBlue = '#bbbbff'
const lightGreen = '#bbffbb'
const darkGreen = '#68e495'
const brown = '#632f2b'
const grey = '#bbbbbb'
const black = '#000000'

// eslint-disable-next-line @typescript-eslint/no-unused-vars
const highlightColors = [
  yellow,
  orange,
  red,
  pink,
  purple,
  darkBlue,
  lightBlue,
  lightGreen,
  darkGreen,
  brown,
  grey,
  black,
]

const examples: Example[] = [
  // {
  //   title: '',
  //   description: null,
  //   exercise: {
  //     format: 'v1',
  //     instruction: {
  //       lines: [
  //         {
  //           contents: [
  //             { kind: 'text', text: 'Blah' },
  //             { kind: 'whitespace' },
  //             { kind: 'text', text: 'blah' },
  //             { kind: 'text', text: '.' },
  //           ],
  //         },
  //       ],
  //     },
  //     example: null,
  //     hint: null,
  //     statement: {
  //       pages: [
  //         {
  //           lines: [
  //             {
  //               contents: [
  //                 { kind: 'text', text: 'Blah' },
  //                 { kind: 'whitespace' },
  //                 { kind: 'text', text: 'blah' },
  //                 { kind: 'text', text: '.' },
  //               ],
  //             },
  //           ],
  //         },
  //       ],
  //     },
  //     reference: null,
  //   },
  // },
  {
    title: 'RCDouble',
    description: null,
    exercise: {
      format: 'v1',
      instruction: {
        lines: [
          {
            contents: [
              { kind: 'text', text: 'Remplace' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'chaque' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'mot' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'colorié' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'par' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'un' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'synonyme' },
              { kind: 'text', text: '.' },
            ],
          },
        ],
      },
      example: {
        lines: [
          {
            contents: [
              { kind: 'text', text: "C'" },
              { kind: 'text', text: 'est' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'un' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'film' },
              { kind: 'whitespace' },
              { kind: 'formatted', highlighted: yellow, contents: [{ kind: 'text', text: 'comique' }] },
              { kind: 'text', text: '.' },
              { kind: 'whitespace' },
              { kind: 'arrow' },
              { kind: 'whitespace' },
              { kind: 'text', text: "C'" },
              { kind: 'text', text: 'est' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'un' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'film' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'drôle' },
              { kind: 'text', text: '.' },
            ],
          },
        ],
      },
      hint: null,
      statement: {
        pages: [
          {
            lines: [
              {
                contents: [
                  { kind: 'text', text: 'a' },
                  { kind: 'text', text: '.' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'Tous' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'ses' },
                  { kind: 'whitespace' },
                  { kind: 'formatted', highlighted: yellow, contents: [{ kind: 'text', text: 'vêtements' }] },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'sont' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'sales' },
                  { kind: 'text', text: '.' },
                  { kind: 'whitespace' },
                  { kind: 'arrow' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'Tous' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'ses' },
                  { kind: 'whitespace' },
                  { kind: 'freeTextInput' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'sont' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'sales' },
                  { kind: 'text', text: '.' },
                ],
              },
              {
                contents: [
                  { kind: 'text', text: 'b' },
                  { kind: 'text', text: '.' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'Elle' },
                  { kind: 'whitespace' },
                  { kind: 'formatted', highlighted: yellow, contents: [{ kind: 'text', text: 'lance' }] },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'du' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'pain' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'aux' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'canards' },
                  { kind: 'text', text: '.' },
                  { kind: 'whitespace' },
                  { kind: 'arrow' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'Elle' },
                  { kind: 'whitespace' },
                  { kind: 'freeTextInput' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'du' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'pain' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'aux' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'canards' },
                  { kind: 'text', text: '.' },
                ],
              },
            ],
          },
        ],
      },
      reference: null,
    },
  },
  {
    title: 'EditTexte',
    description: null,
    exercise: {
      format: 'v1',
      instruction: {
        lines: [
          {
            contents: [
              { kind: 'text', text: 'Complète' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'ce' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'texte' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'en' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'ajoutant' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'les' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'accents' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'aigu' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'ou' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'grave' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'qui' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'manquent' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'sur' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'les' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'lettres' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'e' },
              { kind: 'text', text: '.' },
            ],
          },
        ],
      },
      example: null,
      hint: {
        lines: [
          {
            contents: [
              { kind: 'text', text: 'Aide' },
              { kind: 'text', text: '-' },
              { kind: 'text', text: 'toi' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'de' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'ton' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'dictionnaire' },
              { kind: 'text', text: '.' },
            ],
          },
        ],
      },
      statement: {
        pages: [
          {
            lines: [
              {
                contents: [
                  {
                    kind: 'editableTextInput',
                    showOriginalText: false,
                    contents: [
                      { kind: 'text', text: 'Un' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'beau' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'jour,' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'les' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'viperes' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'donnerent' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'un' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'grand' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'bal' },
                      { kind: 'text', text: '.' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: '[...]' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'Les' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'crapauds' },
                      { kind: 'text', text: ',' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'entierement' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'recouverts' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'd’' },
                      { kind: 'text', text: 'ecailles' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'de' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'poissons' },
                      { kind: 'text', text: ',' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'avançaient' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'en' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'se' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'dandinant' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'comme' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 's’' },
                      { kind: 'text', text: 'ils' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'nageaient' },
                      { kind: 'text', text: '.' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'Les' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'grenouilles' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 's’' },
                      { kind: 'text', text: 'etaient' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'parfume' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'tout' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'le' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'corps' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'et' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'marchaient' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'sur' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'les' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'pattes' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'de' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'derriere' },
                      { kind: 'text', text: '.' },
                    ],
                  },
                ],
              },
            ],
          },
        ],
      },
      reference: {
        contents: [
          { kind: 'text', text: 'Horacio' },
          { kind: 'whitespace' },
          { kind: 'text', text: 'Quiroga' },
          { kind: 'text', text: ',' },
          { kind: 'whitespace' },
          { kind: 'text', text: 'Contes' },
          { kind: 'whitespace' },
          { kind: 'text', text: 'de' },
          { kind: 'whitespace' },
          { kind: 'text', text: 'la' },
          { kind: 'whitespace' },
          { kind: 'text', text: 'forêt' },
          { kind: 'whitespace' },
          { kind: 'text', text: 'vierge' },
          { kind: 'text', text: ',' },
          { kind: 'whitespace' },
          { kind: 'text', text: '©' },
          { kind: 'whitespace' },
          { kind: 'text', text: 'Éditions' },
          { kind: 'whitespace' },
          { kind: 'text', text: 'du' },
          { kind: 'whitespace' },
          { kind: 'text', text: 'Seuil' },
          { kind: 'text', text: ',' },
          { kind: 'whitespace' },
          { kind: 'text', text: '1998' },
        ],
      },
    },
  },
  {
    title: 'Associe',
    description: null,
    exercise: {
      format: 'v1',
      instruction: {
        lines: [
          {
            contents: [
              { kind: 'text', text: 'Associe' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'chaque' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'sujet' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'au' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'verbe' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'qui' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'convient' },
              { kind: 'text', text: '.' },
            ],
          },
        ],
      },
      example: null,
      hint: null,
      statement: {
        pages: [
          {
            lines: [
              {
                contents: [
                  { kind: 'text', text: 'Peter' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'et' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'Anna' },
                  { kind: 'whitespace' },
                  {
                    kind: 'multipleChoicesInput',
                    choices: [
                      { contents: [{ kind: 'text', text: 'participons' }] },
                      { contents: [{ kind: 'text', text: 'allez' }] },
                      { contents: [{ kind: 'text', text: 'marche' }] },
                      { contents: [{ kind: 'text', text: 'déménagent' }] },
                      { contents: [{ kind: 'text', text: 'as' }] },
                    ],
                    showChoicesByDefault: false,
                  },
                ],
              },
            ],
          },
          {
            lines: [
              {
                contents: [
                  { kind: 'text', text: 'Je' },
                  { kind: 'whitespace' },
                  {
                    kind: 'multipleChoicesInput',
                    choices: [
                      { contents: [{ kind: 'text', text: 'participons' }] },
                      { contents: [{ kind: 'text', text: 'allez' }] },
                      { contents: [{ kind: 'text', text: 'marche' }] },
                      { contents: [{ kind: 'text', text: 'déménagent' }] },
                      { contents: [{ kind: 'text', text: 'as' }] },
                    ],
                    showChoicesByDefault: false,
                  },
                ],
              },
            ],
          },
          {
            lines: [
              {
                contents: [
                  { kind: 'text', text: 'Nous' },
                  { kind: 'whitespace' },
                  {
                    kind: 'multipleChoicesInput',
                    choices: [
                      { contents: [{ kind: 'text', text: 'participons' }] },
                      { contents: [{ kind: 'text', text: 'allez' }] },
                      { contents: [{ kind: 'text', text: 'marche' }] },
                      { contents: [{ kind: 'text', text: 'déménagent' }] },
                      { contents: [{ kind: 'text', text: 'as' }] },
                    ],
                    showChoicesByDefault: false,
                  },
                ],
              },
            ],
          },
          {
            lines: [
              {
                contents: [
                  { kind: 'text', text: 'Tu' },
                  { kind: 'whitespace' },
                  {
                    kind: 'multipleChoicesInput',
                    choices: [
                      { contents: [{ kind: 'text', text: 'participons' }] },
                      { contents: [{ kind: 'text', text: 'allez' }] },
                      { contents: [{ kind: 'text', text: 'marche' }] },
                      { contents: [{ kind: 'text', text: 'déménagent' }] },
                      { contents: [{ kind: 'text', text: 'as' }] },
                    ],
                    showChoicesByDefault: false,
                  },
                ],
              },
            ],
          },
          {
            lines: [
              {
                contents: [
                  { kind: 'text', text: 'Vous' },
                  { kind: 'whitespace' },
                  {
                    kind: 'multipleChoicesInput',
                    choices: [
                      { contents: [{ kind: 'text', text: 'participons' }] },
                      { contents: [{ kind: 'text', text: 'allez' }] },
                      { contents: [{ kind: 'text', text: 'marche' }] },
                      { contents: [{ kind: 'text', text: 'déménagent' }] },
                      { contents: [{ kind: 'text', text: 'as' }] },
                    ],
                    showChoicesByDefault: false,
                  },
                ],
              },
            ],
          },
        ],
      },
      reference: null,
    },
  },
  {
    title: 'Classe',
    description: null,
    exercise: {
      format: 'v1',
      instruction: {
        lines: [
          {
            contents: [
              { kind: 'text', text: 'Colorie' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'dans' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'ce' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'texte' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'les' },
              { kind: 'whitespace' },
              {
                kind: 'formatted',
                boxed: true,
                highlighted: yellow,
                contents: [
                  { kind: 'text', text: 'verbes' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'conjugués' },
                ],
              },
              { kind: 'whitespace' },
              { kind: 'text', text: 'en' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'jaune' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'et' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'les' },
              { kind: 'whitespace' },
              {
                kind: 'formatted',
                boxed: true,
                highlighted: pink,
                contents: [
                  { kind: 'text', text: 'verbes' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'à' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'l' },
                  { kind: 'text', text: '’' },
                  { kind: 'text', text: 'infinitif' },
                ],
              },
              { kind: 'whitespace' },
              { kind: 'text', text: 'en' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'rose' },
              { kind: 'text', text: '.' },
            ],
          },
        ],
      },
      example: null,
      hint: null,
      statement: {
        pages: [
          {
            lines: [
              {
                contents: [
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow, pink],
                    contents: [{ kind: 'text', text: 'La' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow, pink],
                    contents: [{ kind: 'text', text: 'tortue' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow, pink],
                    contents: [{ kind: 'text', text: 'leva' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow, pink],
                    contents: [{ kind: 'text', text: 'ses' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow, pink],
                    contents: [{ kind: 'text', text: 'yeux' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow, pink],
                    contents: [{ kind: 'text', text: 'noirs' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow, pink],
                    contents: [{ kind: 'text', text: 'et' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow, pink],
                    contents: [{ kind: 'text', text: 'enfoncés' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow, pink],
                    contents: [{ kind: 'text', text: 'sur' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow, pink],
                    contents: [{ kind: 'text', text: 'le' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow, pink],
                    contents: [{ kind: 'text', text: 'petit' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow, pink],
                    contents: [{ kind: 'text', text: 'garçon' }],
                  },
                  { kind: 'text', text: '.' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: '[…]' },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow, pink],
                    contents: [{ kind: 'text', text: 'Personne' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow, pink],
                    contents: [{ kind: 'text', text: 'ne' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow, pink],
                    contents: [{ kind: 'text', text: 'bougeait' }],
                  },
                  { kind: 'text', text: '.' },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow, pink],
                    contents: [{ kind: 'text', text: 'Puis' }],
                  },
                  { kind: 'text', text: ',' },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow, pink],
                    contents: [{ kind: 'text', text: 'avec' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow, pink],
                    contents: [{ kind: 'text', text: 'une' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow, pink],
                    contents: [{ kind: 'text', text: 'grande' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow, pink],
                    contents: [{ kind: 'text', text: 'dignité' }],
                  },
                  { kind: 'text', text: ',' },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow, pink],
                    contents: [
                      { kind: 'text', text: 'l' },
                      { kind: 'text', text: '’' },
                    ],
                  },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow, pink],
                    contents: [{ kind: 'text', text: 'énorme' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow, pink],
                    contents: [{ kind: 'text', text: 'bête' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow, pink],
                    contents: [{ kind: 'text', text: 'se' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow, pink],
                    contents: [{ kind: 'text', text: 'retourna' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow, pink],
                    contents: [{ kind: 'text', text: 'et' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow, pink],
                    contents: [{ kind: 'text', text: 'se' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow, pink],
                    contents: [{ kind: 'text', text: 'dirigea' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow, pink],
                    contents: [{ kind: 'text', text: 'vers' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow, pink],
                    contents: [{ kind: 'text', text: 'le' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow, pink],
                    contents: [{ kind: 'text', text: 'bord' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow, pink],
                    contents: [{ kind: 'text', text: 'de' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow, pink],
                    contents: [
                      { kind: 'text', text: 'l' },
                      { kind: 'text', text: '’' },
                    ],
                  },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow, pink],
                    contents: [{ kind: 'text', text: 'eau' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow, pink],
                    contents: [{ kind: 'text', text: 'en' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow, pink],
                    contents: [{ kind: 'text', text: 'se' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow, pink],
                    contents: [{ kind: 'text', text: 'dandinant' }],
                  },
                  { kind: 'text', text: ',' },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow, pink],
                    contents: [{ kind: 'text', text: 'sans' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow, pink],
                    contents: [{ kind: 'text', text: 'se' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow, pink],
                    contents: [{ kind: 'text', text: 'presser' }],
                  },
                  { kind: 'text', text: '.' },
                ],
              },
            ],
          },
        ],
      },
      reference: null,
    },
  },
  {
    title: 'RCCadre',
    description: null,
    exercise: {
      format: 'v1',
      instruction: {
        lines: [
          {
            contents: [
              { kind: 'text', text: 'Complète' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'les' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'phrases' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'avec' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'le' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'verbe' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'conjugué' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'au' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'présent' },
              { kind: 'text', text: '.' },
            ],
          },
        ],
      },
      example: null,
      hint: null,
      statement: {
        pages: [
          {
            lines: [
              {
                contents: [{ kind: 'formatted', boxed: true, contents: [{ kind: 'text', text: 'venir' }] }],
              },
              {
                contents: [
                  { kind: 'text', text: 'a' },
                  { kind: 'text', text: '.' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'Il' },
                  { kind: 'whitespace' },
                  { kind: 'freeTextInput' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'me' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'voir' },
                  { kind: 'text', text: '.' },
                ],
              },
            ],
          },
          {
            lines: [
              {
                contents: [{ kind: 'formatted', boxed: true, contents: [{ kind: 'text', text: 'venir' }] }],
              },
              {
                contents: [
                  { kind: 'text', text: 'b' },
                  { kind: 'text', text: '.' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'Nous' },
                  { kind: 'whitespace' },
                  { kind: 'freeTextInput' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'tous' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'les' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'jours' },
                  { kind: 'text', text: '.' },
                ],
              },
            ],
          },
        ],
      },
      reference: null,
    },
  },
  {
    title: 'GenreNombre',
    description: 'A simple case of ChoixMultiple.',
    exercise: {
      format: 'v1',
      instruction: {
        lines: [
          {
            contents: [
              { kind: 'text', text: 'Pour' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'chaque' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'nom' },
              { kind: 'text', text: ',' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'écris' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'son' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'genre' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'et' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'son' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'nombre' },
              { kind: 'text', text: '.' },
            ],
          },
        ],
      },
      example: {
        lines: [
          {
            contents: [
              { kind: 'text', text: 'flûtes' },
              { kind: 'whitespace' },
              { kind: 'arrow' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'féminin' },
              { kind: 'text', text: ',' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'pluriel' },
            ],
          },
        ],
      },
      hint: null,
      statement: {
        pages: [
          {
            lines: [
              {
                contents: [
                  { kind: 'text', text: 'a' },
                  { kind: 'text', text: '.' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'classe' },
                  { kind: 'arrow' },
                  {
                    kind: 'multipleChoicesInput',
                    choices: [
                      { contents: [{ kind: 'text', text: 'féminin' }] },
                      { contents: [{ kind: 'text', text: 'masculin' }] },
                    ],
                    showChoicesByDefault: false,
                  },
                  { kind: 'text', text: ',' },
                  { kind: 'whitespace' },
                  {
                    kind: 'multipleChoicesInput',
                    choices: [
                      { contents: [{ kind: 'text', text: 'singulier' }] },
                      { contents: [{ kind: 'text', text: 'pluriel' }] },
                    ],
                    showChoicesByDefault: false,
                  },
                ],
              },
              {
                contents: [
                  { kind: 'text', text: 'cachots' },
                  { kind: 'arrow' },
                  {
                    kind: 'multipleChoicesInput',
                    choices: [
                      { contents: [{ kind: 'text', text: 'féminin' }] },
                      { contents: [{ kind: 'text', text: 'masculin' }] },
                    ],
                    showChoicesByDefault: false,
                  },
                  { kind: 'text', text: ',' },
                  { kind: 'whitespace' },
                  {
                    kind: 'multipleChoicesInput',
                    choices: [
                      { contents: [{ kind: 'text', text: 'singulier' }] },
                      { contents: [{ kind: 'text', text: 'pluriel' }] },
                    ],
                    showChoicesByDefault: false,
                  },
                ],
              },
            ],
          },
        ],
      },
      reference: null,
    },
  },
  {
    title: 'Vrai/Faux',
    description: 'A simple case of ChoixMultiple.',
    exercise: {
      format: 'v1',
      instruction: {
        lines: [
          {
            contents: [
              { kind: 'text', text: 'Réponds' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'par' },
              { kind: 'whitespace' },
              {
                kind: 'formatted',
                bold: false,
                italic: false,
                underlined: false,
                boxed: true,
                highlighted: null,
                contents: [{ kind: 'text', text: 'vrai' }],
              },
              { kind: 'whitespace' },
              { kind: 'text', text: 'ou' },
              { kind: 'whitespace' },
              {
                kind: 'formatted',
                bold: false,
                italic: false,
                underlined: false,
                boxed: true,
                highlighted: null,
                contents: [{ kind: 'text', text: 'faux' }],
              },
              { kind: 'text', text: '.' },
            ],
          },
        ],
      },
      example: null,
      hint: null,
      statement: {
        pages: [
          {
            lines: [
              {
                contents: [
                  { kind: 'text', text: 'a' },
                  { kind: 'text', text: '.' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'A' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'la' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: '2' },
                  { kind: 'text', text: 'e' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'personne' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'du' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'singulier' },
                  { kind: 'text', text: ',' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'les' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'verbes' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'aller' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'et' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'venir' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'prennent' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'un' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 's' },
                  { kind: 'text', text: '.' },
                ],
              },
              {
                contents: [
                  { kind: 'arrow' },
                  {
                    kind: 'multipleChoicesInput',
                    choices: [
                      { contents: [{ kind: 'text', text: 'Vrai' }] },
                      { contents: [{ kind: 'text', text: 'Faux' }] },
                    ],
                    showChoicesByDefault: true,
                  },
                ],
              },
            ],
          },
        ],
      },
      reference: null,
    },
  },
  {
    title: 'TransformePhrase',
    description: 'An alternative is to use "kind": "editableTextInput" as in the "Edit sentence" example below.',
    exercise: {
      format: 'v1',
      instruction: {
        lines: [
          {
            contents: [
              { kind: 'text', text: 'Transforme' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'chaque' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'couple' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'de' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'phrases' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'pour' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'en' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'faire' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'une' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'seule' },
              { kind: 'text', text: '.' },
            ],
          },
        ],
      },
      example: {
        lines: [
          {
            contents: [
              { kind: 'text', text: 'Léa' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'souffle' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'les' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'bougies' },
              { kind: 'text', text: '.' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'Léo' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'souffle' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'les' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'bougies' },
              { kind: 'text', text: '.' },
            ],
          },
          {
            contents: [
              { kind: 'arrow' },
              { kind: 'text', text: 'Léa' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'et' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'Léo' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'soufflent' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'les' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'bougies' },
              { kind: 'text', text: '.' },
            ],
          },
        ],
      },
      hint: null,
      statement: {
        pages: [
          {
            lines: [
              {
                contents: [
                  { kind: 'text', text: 'a' },
                  { kind: 'text', text: '.' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'Le' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'manchot' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'glisse' },
                  { kind: 'text', text: '.' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'Le' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'pingouin' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'glisse' },
                  { kind: 'text', text: '.' },
                ],
              },
              {
                contents: [{ kind: 'arrow' }, { kind: 'freeTextInput' }],
              },
            ],
          },
          {
            lines: [
              {
                contents: [
                  { kind: 'text', text: 'b' },
                  { kind: 'text', text: '.' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'Kiki' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 's' },
                  { kind: 'text', text: '’' },
                  { kind: 'text', text: 'approche' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'de' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'moi.' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'Loulou' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 's' },
                  { kind: 'text', text: '’' },
                  { kind: 'text', text: 'approche' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'de' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'moi' },
                  { kind: 'text', text: '.' },
                ],
              },
              {
                contents: [{ kind: 'arrow' }, { kind: 'freeTextInput' }],
              },
            ],
          },
        ],
      },
      reference: null,
    },
  },
  {
    title: 'TransformeMot',
    description: null,
    exercise: {
      format: 'v1',
      instruction: {
        lines: [
          {
            contents: [
              { kind: 'text', text: 'Écris' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'l' },
              { kind: 'text', text: '’' },
              { kind: 'text', text: 'infinitif' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'des' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'verbes' },
              { kind: 'text', text: '.' },
            ],
          },
        ],
      },
      example: null,
      hint: null,
      statement: {
        pages: [
          {
            lines: [
              {
                contents: [
                  { kind: 'text', text: 'a' },
                  { kind: 'text', text: '.' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'je' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'choisis' },
                  { kind: 'arrow' },
                  { kind: 'freeTextInput' },
                ],
              },
              {
                contents: [
                  { kind: 'text', text: 'il' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'prends' },
                  { kind: 'arrow' },
                  { kind: 'freeTextInput' },
                ],
              },
              {
                contents: [
                  { kind: 'text', text: 'vous' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'salissez' },
                  { kind: 'arrow' },
                  { kind: 'freeTextInput' },
                ],
              },
            ],
          },
          {
            lines: [
              {
                contents: [
                  { kind: 'text', text: 'b' },
                  { kind: 'text', text: '.' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'elle' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'pétille' },
                  { kind: 'arrow' },
                  { kind: 'freeTextInput' },
                ],
              },
              {
                contents: [
                  { kind: 'text', text: 'elle' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'voit' },
                  { kind: 'arrow' },
                  { kind: 'freeTextInput' },
                ],
              },
              {
                contents: [
                  { kind: 'text', text: 'il' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'galope' },
                  { kind: 'arrow' },
                  { kind: 'freeTextInput' },
                ],
              },
              {
                contents: [
                  { kind: 'text', text: 'je' },
                  { kind: 'whitespace' },
                  { kind: 'text', text: 'reçois' },
                  { kind: 'arrow' },
                  { kind: 'freeTextInput' },
                ],
              },
            ],
          },
        ],
      },
      reference: null,
    },
  },
  {
    title: 'CocheMot',
    description:
      'Note that punctuation is also selectable in this example. If this is not wanted, you should remove the "kind": "selectableInput" around punctuation elements.',
    exercise: {
      format: 'v1',
      instruction: {
        lines: [
          {
            contents: [
              { kind: 'text', text: 'Colorie' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'tous' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'les' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'déterminants' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'de' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'ce' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'texte' },
              { kind: 'text', text: '.' },
            ],
          },
        ],
      },
      example: null,
      hint: null,
      statement: {
        pages: [
          {
            lines: [
              {
                contents: [
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow],
                    contents: [{ kind: 'text', text: 'Une' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow],
                    contents: [{ kind: 'text', text: 'éolienne' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow],
                    contents: [{ kind: 'text', text: 'est' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow],
                    contents: [{ kind: 'text', text: 'une' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow],
                    contents: [{ kind: 'text', text: 'centrale' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow],
                    contents: [{ kind: 'text', text: 'électrique' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow],
                    contents: [{ kind: 'text', text: 'comme' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow],
                    contents: [{ kind: 'text', text: 'toutes' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow],
                    contents: [{ kind: 'text', text: 'les' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow],
                    contents: [{ kind: 'text', text: 'autres' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow],
                    contents: [{ kind: 'text', text: ':' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow],
                    contents: [{ kind: 'text', text: 'une' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow],
                    contents: [{ kind: 'text', text: 'turbine' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow],
                    contents: [{ kind: 'text', text: '(' }],
                  },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow],
                    contents: [{ kind: 'text', text: 'l’' }],
                  },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow],
                    contents: [{ kind: 'text', text: 'hélice' }],
                  },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow],
                    contents: [{ kind: 'text', text: ')' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow],
                    contents: [{ kind: 'text', text: 'est' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow],
                    contents: [{ kind: 'text', text: 'mise' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow],
                    contents: [{ kind: 'text', text: 'en' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow],
                    contents: [{ kind: 'text', text: 'rotation' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow],
                    contents: [{ kind: 'text', text: 'par' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow],
                    contents: [{ kind: 'text', text: 'le' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow],
                    contents: [{ kind: 'text', text: 'vent' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow],
                    contents: [{ kind: 'text', text: ';' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow],
                    contents: [{ kind: 'text', text: 'elle' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow],
                    contents: [{ kind: 'text', text: 'est' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow],
                    contents: [{ kind: 'text', text: 'couplée' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow],
                    contents: [{ kind: 'text', text: 'à' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow],
                    contents: [{ kind: 'text', text: 'un' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow],
                    contents: [{ kind: 'text', text: 'alternateur' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow],
                    contents: [{ kind: 'text', text: 'qui' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow],
                    contents: [{ kind: 'text', text: 'produit' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow],
                    contents: [{ kind: 'text', text: 'de' }],
                  },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow],
                    contents: [{ kind: 'text', text: 'l’électricité' }],
                  },
                  {
                    kind: 'selectableInput',
                    boxed: false,
                    colors: [yellow],
                    contents: [{ kind: 'text', text: '.' }],
                  },
                ],
              },
            ],
          },
        ],
      },
      reference: null,
    },
  },
  {
    title: 'CochePhrase',
    description: null,
    exercise: {
      format: 'v1',
      instruction: {
        lines: [
          {
            contents: [
              { kind: 'text', text: 'Colorie' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'uniquement' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'les' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'phrases' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'exactes' },
              { kind: 'text', text: '.' },
            ],
          },
        ],
      },
      example: null,
      hint: null,
      statement: {
        pages: [
          {
            lines: [
              {
                contents: [
                  { kind: 'text', text: 'a' },
                  { kind: 'text', text: '.' },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: true,
                    colors: [yellow],
                    contents: [
                      { kind: 'text', text: 'Une' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'phrase' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'se' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'termine' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'par' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'un' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'point' },
                      { kind: 'text', text: ',' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'un' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'point' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'd' },
                      { kind: 'text', text: '’' },
                      { kind: 'text', text: 'exclamation' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'ou' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'un' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'point' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'd' },
                      { kind: 'text', text: '’' },
                      { kind: 'text', text: 'interrogation' },
                      { kind: 'text', text: '.' },
                    ],
                  },
                ],
              },
              {
                contents: [
                  { kind: 'text', text: 'b' },
                  { kind: 'text', text: '.' },
                  { kind: 'whitespace' },
                  {
                    kind: 'selectableInput',
                    boxed: true,
                    colors: [yellow],
                    contents: [
                      { kind: 'text', text: 'Si' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'une' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'suite' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'de' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'mots' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'n' },
                      { kind: 'text', text: '’' },
                      { kind: 'text', text: 'a' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'pas' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'de' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'sens,' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'mais' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'qu' },
                      { kind: 'text', text: '’' },
                      { kind: 'text', text: 'elle' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'commence' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'par' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'une' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'majuscule' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'et' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'se' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'termine' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'par' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'un' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'point' },
                      { kind: 'text', text: ',' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'c' },
                      { kind: 'text', text: '’' },
                      { kind: 'text', text: 'est' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'une' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'phrase' },
                      { kind: 'text', text: '.' },
                    ],
                  },
                ],
              },
            ],
          },
        ],
      },
      reference: null,
    },
  },
  {
    title: 'Swappable inputs',
    description: null,
    exercise: {
      format: 'v1',
      instruction: {
        lines: [],
      },
      example: null,
      hint: null,
      statement: {
        pages: [
          {
            lines: [
              {
                contents: [
                  { kind: 'swappableInput', contents: [{ kind: 'text', text: 'A' }] },
                  { kind: 'swappableInput', contents: [{ kind: 'text', text: 'B' }] },
                  { kind: 'swappableInput', contents: [{ kind: 'text', text: 'C' }] },
                ],
              },
            ],
          },
        ],
      },
      reference: null,
    },
  },
  {
    title: 'EditPhrase',
    description: null,
    exercise: {
      format: 'v1',
      instruction: {
        lines: [
          {
            contents: [
              { kind: 'text', text: 'Recopie' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'chaque' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'phrase' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'en' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'rétablissant' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'la' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'ponctuation' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'comme' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'dans' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'l' },
              { kind: 'text', text: "'" },
              { kind: 'text', text: 'exemple' },
              { kind: 'text', text: '.' },
            ],
          },
        ],
      },
      example: {
        lines: [
          {
            contents: [
              { kind: 'text', text: 'la' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'nuit' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'dans' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'le' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'ciel' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'les' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'étoiles' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'brillent' },
            ],
          },
          {
            contents: [
              { kind: 'arrow' },
              { kind: 'text', text: 'La' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'nuit' },
              { kind: 'text', text: ',' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'dans' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'le' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'ciel' },
              { kind: 'text', text: ',' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'les' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'étoiles' },
              { kind: 'whitespace' },
              { kind: 'text', text: 'brillent' },
              { kind: 'text', text: '.' },
            ],
          },
        ],
      },
      hint: null,
      statement: {
        pages: [
          {
            lines: [
              {
                contents: [
                  { kind: 'text', text: 'a' },
                  { kind: 'text', text: '.' },
                  { kind: 'whitespace' },
                  {
                    kind: 'editableTextInput',
                    showOriginalText: true,
                    contents: [
                      { kind: 'text', text: 'souvent' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'dans' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'le' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'noir' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'j' },
                      { kind: 'text', text: "'" },
                      { kind: 'text', text: 'ai' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'peur' },
                    ],
                  },
                ],
              },
            ],
          },
          {
            lines: [
              {
                contents: [
                  { kind: 'text', text: 'b' },
                  { kind: 'text', text: '.' },
                  { kind: 'whitespace' },
                  {
                    kind: 'editableTextInput',
                    showOriginalText: true,
                    contents: [
                      { kind: 'text', text: 'parfois' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'en' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'plein' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'jour' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'j' },
                      { kind: 'text', text: "'" },
                      { kind: 'text', text: 'ai' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'peur' },
                      { kind: 'whitespace' },
                      { kind: 'text', text: 'aussi' },
                    ],
                  },
                ],
              },
            ],
          },
        ],
      },
      reference: null,
    },
  },
]
</script>

<template>
  <div style="padding-left: 5px; padding-right: 5px">
    <h1>{{ t('examples') }}</h1>
    <template v-for="example in examples" :key="example.title">
      <div style="margin-bottom: 10px">
        <ExamplesViewExercise :example />
      </div>
    </template>
  </div>
</template>

<i18n>
en:
  examples: Examples
fr:
  examples: Exemples
</i18n>
