import { visit } from './utils'

describe('The index view', () => {
  beforeEach(() => {
    cy.viewport(1600, 800)
    visit('/')
    cy.get('[data-cy="identified-user"]').type('Alice', { delay: 0 })
    cy.get('[data-cy="identified-user-ok"]').click()
  })

  it('paginates the existing adaptation batches', () => {
    cy.request('POST', 'http://fixtures-loader/load?fixtures=20-adaptation-batches')
    cy.visit('/')
    cy.get('a:contains("Batch A")').should('have.length', 20)
    cy.get('a:contains("Batch A")').eq(0).should('contain', 'Batch A20')
    cy.get('a:contains("Batch A")').eq(19).should('contain', 'Batch A1')
    cy.get('button:contains("Load more...")').eq(2).should('be.disabled')

    cy.request('POST', 'http://fixtures-loader/load?fixtures=21-adaptation-batches')
    cy.visit('/')
    cy.get('a:contains("Batch A")').should('have.length', 20)
    cy.get('a:contains("Batch A")').eq(0).should('contain', 'Batch A21')
    cy.get('a:contains("Batch A")').eq(19).should('contain', 'Batch A2')
    cy.get('button:contains("Load more...")').eq(2).should('be.enabled').click()
    cy.get('a:contains("Batch A")').should('have.length', 21)
    cy.get('a:contains("Batch A")').eq(0).should('contain', 'Batch A21')
    cy.get('a:contains("Batch A")').eq(19).should('contain', 'Batch A2')
    cy.get('a:contains("Batch A")').eq(20).should('contain', 'Batch A1')
    cy.get('button:contains("Load more...")').eq(2).should('be.disabled')

    cy.request('POST', 'http://fixtures-loader/load?fixtures=70-adaptation-batches')
    cy.visit('/')
    cy.get('a:contains("Batch A")').should('have.length', 20)
    cy.get('a:contains("Batch A")').eq(0).should('contain', 'Batch A70')
    cy.get('a:contains("Batch A")').eq(19).should('contain', 'Batch A51')
    cy.get('button:contains("Load more...")').eq(2).should('be.enabled').click()
    cy.get('a:contains("Batch A")').should('have.length', 40)
    cy.get('a:contains("Batch A")').eq(0).should('contain', 'Batch A70')
    cy.get('a:contains("Batch A")').eq(19).should('contain', 'Batch A51')
    cy.get('a:contains("Batch A")').eq(20).should('contain', 'Batch A50')
    cy.get('a:contains("Batch A")').eq(39).should('contain', 'Batch A31')
    cy.get('button:contains("Load more...")').eq(2).should('be.enabled').click()
    cy.get('a:contains("Batch A")').should('have.length', 60)
    cy.get('a:contains("Batch A")').eq(0).should('contain', 'Batch A70')
    cy.get('a:contains("Batch A")').eq(19).should('contain', 'Batch A51')
    cy.get('a:contains("Batch A")').eq(20).should('contain', 'Batch A50')
    cy.get('a:contains("Batch A")').eq(39).should('contain', 'Batch A31')
    cy.get('a:contains("Batch A")').eq(40).should('contain', 'Batch A30')
    cy.get('a:contains("Batch A")').eq(59).should('contain', 'Batch A11')
    cy.get('button:contains("Load more...")').eq(2).should('be.enabled').click()
    cy.get('a:contains("Batch A")').should('have.length', 70)
    cy.get('a:contains("Batch A")').eq(0).should('contain', 'Batch A70')
    cy.get('a:contains("Batch A")').eq(19).should('contain', 'Batch A51')
    cy.get('a:contains("Batch A")').eq(20).should('contain', 'Batch A50')
    cy.get('a:contains("Batch A")').eq(39).should('contain', 'Batch A31')
    cy.get('a:contains("Batch A")').eq(40).should('contain', 'Batch A30')
    cy.get('a:contains("Batch A")').eq(59).should('contain', 'Batch A11')
    cy.get('a:contains("Batch A")').eq(60).should('contain', 'Batch A10')
    cy.get('a:contains("Batch A")').eq(69).should('contain', 'Batch A1')
    cy.get('button:contains("Load more...")').eq(2).should('be.disabled')
  })
})
