name: patty-dev

services:
  db:
    image: postgres:15
    tmpfs:
      - /var/lib/postgresql/data
    env_file:
      - db/env
    healthcheck:
      test: ["CMD", "pg_isready", "--timeout=0", "--dbname=db", "--username=admin" ]
      interval: 0.5s

  adminer:
    image: adminer:4
    # @todo Set default DB type, host and user (see https://github.com/TimWolla/docker-adminer/issues/39#issuecomment-408568987)

  generated-files-cleaner:
    image: patty-dev_backend
    pull_policy: never
    volumes:
      - ..:/app
      - ./backend/pip-packages:/home/patty/.local
    working_dir: /app
    env_file:
      - backend/env
      - backend/secrets.env
    command: [
      "rm", "-f",
      "backend/openapi.json",
      "backend/adapted-exercise-schema.json",
      "frontend/src/openapi.ts",
      "backend/patty/adaptation/templates/adaptation-export/index.html",
    ]

  adaptation-export-template-continuous-generator:
    image: patty-dev_frontend
    pull_policy: never
    volumes:
      - ..:/app
      - ./frontend/cache:/home/patty/.cache
    working_dir: /app/frontend
    environment:
      PATTY_ENTRY_POINT_NAME: adaptation-export
    command: ["npx", "vite", "build", "--watch", "--mode", "development", "--outDir", "../backend/patty/adaptation/templates/adaptation-export", "--emptyOutDir"]
    depends_on:
      generated-files-cleaner:
        condition: service_completed_successfully
      npm-installer:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "test", "-f", "/app/backend/patty/adaptation/templates/adaptation-export/index.html"]
      interval: 0.5s
      retries: 12

  backend-shell:
    image: patty-dev_backend
    build:
      context: ..
      dockerfile: dev-env/backend/docker/Dockerfile
      args:
        USER_ID: $USER_ID
        GROUP_ID: $GROUP_ID
    volumes:
      - ..:/app
      - ./backend/pip-packages:/home/patty/.local
    working_dir: /app/backend
    env_file:
      - backend/env
      - backend/secrets.env
    init: true
    command: ["sleep", "infinity"]
  pip-installer:
    image: patty-dev_backend
    pull_policy: never
    volumes:
      - ..:/app
      - ./backend/pip-packages:/home/patty/.local
    working_dir: /app/backend
    command: ["pip", "install", "--user", "-r", "requirements-dev.txt", "-r", "requirements-run.txt"]
  migrator:
    image: patty-dev_backend
    pull_policy: never
    volumes:
      - ..:/app
      - ./backend/pip-packages:/home/patty/.local
    working_dir: /app/backend/patty
    env_file:
      - backend/env
      - backend/secrets.env
    command: ["alembic", "upgrade", "head"]
    depends_on:
      pip-installer:
        condition: service_completed_successfully
      db:
        condition: service_healthy
  data-loader:
    image: patty-dev_backend
    pull_policy: never
    volumes:
      - ..:/app
      - ./backend/pip-packages:/home/patty/.local
    working_dir: /app/backend
    env_file:
      - backend/env
      - backend/secrets.env
    command: ["python", "-m", "patty", "load-fixtures", "dummy-adaptation-strategy", "default-adaptation-input"]
    depends_on:
      migrator:
        condition: service_completed_successfully
  backend:
    image: patty-dev_backend
    pull_policy: never
    volumes:
      - ..:/app
      - ./backend/pip-packages:/home/patty/.local
    working_dir: /app/backend
    env_file:
      - backend/env
      - backend/secrets.env
    command: ["uvicorn", "patty.asgi:app", "--reload", "--host", "0.0.0.0", "--port", "80"]
    depends_on:
      adaptation-export-template-continuous-generator:
        condition: service_healthy
      data-loader:
        condition: service_completed_successfully
  openapi-json-first-time-generator:
    image: patty-dev_backend
    pull_policy: never
    volumes:
      - ..:/app
      - ./backend/pip-packages:/home/patty/.local
    working_dir: /app/backend
    env_file:
      - backend/env
      - backend/secrets.env
    command: ["bash", "-c", 'echo "Generating backend/openapi.json for the first time" && python -m patty openapi openapi.json']
    depends_on:
      generated-files-cleaner:
        condition: service_completed_successfully
      pip-installer:
        condition: service_completed_successfully
  openapi-json-continuous-generator:
    image: patty-dev_backend
    pull_policy: never
    volumes:
      - ..:/app
      - ./backend/pip-packages:/home/patty/.local
    working_dir: /app/backend
    env_file:
      - backend/env
      - backend/secrets.env
    init: true
    command: [
      "watchmedo", "shell-command",
      "--command", 'test $${watch_event_type} = closed && echo "Updating backend/openapi.json because $${watch_src_path} changed" && python -m patty openapi openapi.json',
      "--recursive",
      "--ignore-directories",
      "--ignore-patterns", "*/__pycache__/*",
      "patty"
    ]
    depends_on:
      openapi-json-first-time-generator:
        condition: service_completed_successfully
  adapted-exercise-json-schema-first-time-generator:
    image: patty-dev_backend
    pull_policy: never
    volumes:
      - ..:/app
      - ./backend/pip-packages:/home/patty/.local
    working_dir: /app/backend
    env_file:
      - backend/env
      - backend/secrets.env
    command: ["bash", "-c", 'echo "Generating backend/adapted-exercise-schema.json for the first time" && python -m patty adapted-exercise-schema adapted-exercise-schema.json']
    depends_on:
      generated-files-cleaner:
        condition: service_completed_successfully
      pip-installer:
        condition: service_completed_successfully
  adapted-exercise-json-schema-continuous-generator:
    image: patty-dev_backend
    pull_policy: never
    volumes:
      - ..:/app
      - ./backend/pip-packages:/home/patty/.local
    working_dir: /app/backend
    env_file:
      - backend/env
      - backend/secrets.env
    init: true
    command: [
      "watchmedo", "shell-command",
      "--command", 'test $${watch_event_type} = closed && echo "Updating backend/adapted-exercise-schema.json because $${watch_src_path} changed" && python -m patty adapted-exercise-schema adapted-exercise-schema.json',
      "--recursive",
      "--ignore-directories",
      "--ignore-patterns", "*/__pycache__/*",
      "patty"
    ]
    depends_on:
      adapted-exercise-json-schema-first-time-generator:
        condition: service_completed_successfully
  fixtures-loader:
    image: patty-dev_backend
    pull_policy: never
    volumes:
      - ..:/app
      - ./backend/pip-packages:/home/patty/.local
    working_dir: /app/backend
    env_file:
      - backend/env
      - backend/secrets.env
    command: ["uvicorn", "patty.fixtures:app", "--reload", "--host", "0.0.0.0", "--port", "80"]
    depends_on:
      data-loader:
        condition: service_completed_successfully

  frontend-shell:
    image: patty-dev_frontend
    build:
      context: ..
      dockerfile: dev-env/frontend/docker/Dockerfile
      args:
        USER_ID: $USER_ID
        GROUP_ID: $GROUP_ID
    volumes:
      - ..:/app
      - ./frontend/cache:/home/patty/.cache
      - /tmp/.X11-unix:/tmp/.X11-unix  # Allow running GUI apps in container, displaying on host
    working_dir: /app/frontend
    environment:
      PATTY_ENTRY_POINT_NAME: frontend
    init: true
    command: ["sleep", "infinity"]
    ports:
      - 6868:6868  # For 'npx cypress-image-diff-html-report start'
  npm-installer:
    image: patty-dev_frontend
    pull_policy: never
    volumes:
      - ..:/app
      - ./frontend/cache:/home/patty/.cache
    working_dir: /app/frontend
    command: ["npm", "install"]
  cypress-installer:
    image: patty-dev_frontend
    pull_policy: never
    volumes:
      - ..:/app
      - ./frontend/cache:/home/patty/.cache
    working_dir: /app/frontend
    command: ["npx", "cypress", "install"]
    depends_on:
      npm-installer:
        condition: service_completed_successfully
  openapi-ts-continuous-generator:
    image: patty-dev_frontend
    pull_policy: never
    volumes:
      - ..:/app
      - ./frontend/cache:/home/patty/.cache
    working_dir: /app/frontend
    environment:
      SHELL: bash
    command: ["npx", "chokidar", "../backend/openapi.json", "--silent", "--initial", "--command", "echo 'Updating frontend/openapi.ts because backend/openapi.json changed' && npx openapi-typescript ../backend/openapi.json | npx prettier --parser typescript >src/openapi.ts"]
    depends_on:
      npm-installer:
        condition: service_completed_successfully
      openapi-json-continuous-generator:
        condition: service_started
  frontend:
    image: patty-dev_frontend
    pull_policy: never
    volumes:
      - ..:/app
      - ./frontend/cache:/home/patty/.cache
    working_dir: /app/frontend
    environment:
      PATTY_ENTRY_POINT_NAME: frontend
    command: ["npx", "vite", "--host", "0.0.0.0", "--port", "80", "--strictPort"]
    depends_on:
      openapi-ts-continuous-generator:
        condition: service_started
      adapted-exercise-json-schema-continuous-generator:
        condition: service_started

  fanout:
    image: nginx:latest
    ports:
      - 8080:8080
    volumes:
      - ./fanout/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - adminer
      - backend
      - frontend
